(cl:in-package custom_msgs-msg)
(cl:export '(ID-VAL
          ID
          BBOX_POINT-VAL
          BBOX_POINT
          TYPE-VAL
          TYPE
          VX-VAL
          VX
          VY-VAL
          VY
          V-VAL
          V
          LWH-VAL
          LWH
          X_POS-VAL
          X_POS
          Y_POS-VAL
          Y_POS
          S_POS-VAL
          S_POS
          D_POS-VAL
          D_POS
          LIDAR_X_POS-VAL
          LIDAR_X_POS
          LIDAR_Y_POS-VAL
          LIDAR_Y_POS
          LIDAR_Z_POS-VAL
          LIDAR_Z_POS
))