(cl:in-package custom_msgs-msg)
(cl:export '(HEAD-VAL
          HEAD
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING-VAL
          HEADING
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          SPEED2D-VAL
          SPEED2D
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          POSE_TYPE-VAL
          POSE_TYPE
          GPSTIME-VAL
          GPSTIME
          INS_STATUS-VAL
          INS_STATUS
          LAT_VARI-VAL
          LAT_VARI
          LON_VARI-VAL
          LON_VARI
))