(cl:in-package custom_msgs-msg)
(cl:export '(HEAD-VAL
          HEAD
          APA_TRANSPRNDSHIFTENABLE-VAL
          APA_TRANSPRNDSHIFTENABLE
          APA_TRANSPRNDSHIFTREQVALID-VAL
          APA_TRANSPRNDSHIFTREQVALID
          APA_TRANSPRNDSHIFTREQUEST-VAL
          APA_TRANSPRNDSHIFTREQUEST
))