uint8  clutchGear        #旋耕变速箱挡位 0:低，1：高
uint8  clutchEngaged     #旋耕使能 0:无效，1：有效
uint8  Rotary_enable     #沤肥机使能 0：无效，1：有效
uint8  Rotary_sp_up      #沤肥机转速提升 0：无效，1：有效
uint8  Rotary_sp_contain #沤肥机转速保持 0：无效，1：有效
uint8  Rotary_sp_down    #沤肥机转速下降 0：无效，1：有效
uint8  ACU_Top_Height    #控制选耕高度 
uint8  ACU_oil           #控制油门 
uint16 GO_FRONT         #控制车辆前行
uint16 GO_BACK          #控制车辆后退
uint16 GO_LEFT          #控制车辆左转
uint16 GO_RIGHT         #控制车辆右转