# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/WarnRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WarnRequest(genpy.Message):
  _md5sum = "8a4d12632564889545d9dfc693560f12"
  _type = "custom_msgs/WarnRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#------------------------------
#异常报警服务
#------------------------------
uint8  source   #消息来源
uint8  code     #错误码
"""
  __slots__ = ['source','code']
  _slot_types = ['uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       source,code

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WarnRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.source is None:
        self.source = 0
      if self.code is None:
        self.code = 0
    else:
      self.source = 0
      self.code = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.source, _x.code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.source, _x.code,) = _get_struct_2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.source, _x.code))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.source, _x.code,) = _get_struct_2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/WarnResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WarnResponse(genpy.Message):
  _md5sum = "207ef8cbd2bf5ece28c6335dff80736f"
  _type = "custom_msgs/WarnResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8   isLidarOK
uint8   isNaviOK
uint8   isCtrlOK
uint8   isXavierOK


#----------请按照如下注释进行赋值调用服务-----------------

#------获取状态--------
#source-->  0
# 
#无异常申报，但需要获取状态source赋值为0
#-------------------

#------lidar--------
#source-->  1
#code  -->  0x00: 正常 
#           0x01：(某某)雷达错误
#           0x02：(某某)雷达错误
#-------------------

#------navi--------
#source-->  2
#code  -->  0x00: 正常 
#           0x01：
#           0x02：
#-------------------

#------ctrl--------
#source-->  3
#code  -->  0x00: 正常 
#           0x01：
#           0x02：
#-------------------
"""
  __slots__ = ['isLidarOK','isNaviOK','isCtrlOK','isXavierOK']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isLidarOK,isNaviOK,isCtrlOK,isXavierOK

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WarnResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.isLidarOK is None:
        self.isLidarOK = 0
      if self.isNaviOK is None:
        self.isNaviOK = 0
      if self.isCtrlOK is None:
        self.isCtrlOK = 0
      if self.isXavierOK is None:
        self.isXavierOK = 0
    else:
      self.isLidarOK = 0
      self.isNaviOK = 0
      self.isCtrlOK = 0
      self.isXavierOK = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.isLidarOK, _x.isNaviOK, _x.isCtrlOK, _x.isXavierOK))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.isLidarOK, _x.isNaviOK, _x.isCtrlOK, _x.isXavierOK,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.isLidarOK, _x.isNaviOK, _x.isCtrlOK, _x.isXavierOK))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.isLidarOK, _x.isNaviOK, _x.isCtrlOK, _x.isXavierOK,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
class Warn(object):
  _type          = 'custom_msgs/Warn'
  _md5sum = 'aa3e75dde8fd6fb3a237b3eef4655d49'
  _request_class  = WarnRequest
  _response_class = WarnResponse
