# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/LidarRawObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class LidarRawObject(genpy.Message):
  _md5sum = "b51c36a6f4165e7b94950b3ee65d1f06"
  _type = "custom_msgs/LidarRawObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#------------------------------
#通过激光雷达检测出的目标
#------------------------------


geometry_msgs/Point[8]    bbox_point  #目标边框的8个顶点


geometry_msgs/Vector3     lwh         #x,y,z分别为目标的长宽高，待定
float32                   x_pos       #x位置，待定
float32                   y_pos       #y位置，待定
float32                   z_pos       #

float32                   lidar_x_pos       #储存雷达坐标，用于目标跟踪
float32                   lidar_y_pos       
float32                   lidar_z_pos
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['bbox_point','lwh','x_pos','y_pos','z_pos','lidar_x_pos','lidar_y_pos','lidar_z_pos']
  _slot_types = ['geometry_msgs/Point[8]','geometry_msgs/Vector3','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bbox_point,lwh,x_pos,y_pos,z_pos,lidar_x_pos,lidar_y_pos,lidar_z_pos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LidarRawObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.bbox_point is None:
        self.bbox_point = [geometry_msgs.msg.Point() for _ in range(8)]
      if self.lwh is None:
        self.lwh = geometry_msgs.msg.Vector3()
      if self.x_pos is None:
        self.x_pos = 0.
      if self.y_pos is None:
        self.y_pos = 0.
      if self.z_pos is None:
        self.z_pos = 0.
      if self.lidar_x_pos is None:
        self.lidar_x_pos = 0.
      if self.lidar_y_pos is None:
        self.lidar_y_pos = 0.
      if self.lidar_z_pos is None:
        self.lidar_z_pos = 0.
    else:
      self.bbox_point = [geometry_msgs.msg.Point() for _ in range(8)]
      self.lwh = geometry_msgs.msg.Vector3()
      self.x_pos = 0.
      self.y_pos = 0.
      self.z_pos = 0.
      self.lidar_x_pos = 0.
      self.lidar_y_pos = 0.
      self.lidar_z_pos = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.bbox_point) != 8:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (8, len(self.bbox_point), 'self.bbox_point')))
      for val1 in self.bbox_point:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3d6f().pack(_x.lwh.x, _x.lwh.y, _x.lwh.z, _x.x_pos, _x.y_pos, _x.z_pos, _x.lidar_x_pos, _x.lidar_y_pos, _x.lidar_z_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bbox_point is None:
        self.bbox_point = None
      if self.lwh is None:
        self.lwh = geometry_msgs.msg.Vector3()
      end = 0
      self.bbox_point = []
      for i in range(0, 8):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.bbox_point.append(val1)
      _x = self
      start = end
      end += 48
      (_x.lwh.x, _x.lwh.y, _x.lwh.z, _x.x_pos, _x.y_pos, _x.z_pos, _x.lidar_x_pos, _x.lidar_y_pos, _x.lidar_z_pos,) = _get_struct_3d6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.bbox_point) != 8:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (8, len(self.bbox_point), 'self.bbox_point')))
      for val1 in self.bbox_point:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3d6f().pack(_x.lwh.x, _x.lwh.y, _x.lwh.z, _x.x_pos, _x.y_pos, _x.z_pos, _x.lidar_x_pos, _x.lidar_y_pos, _x.lidar_z_pos))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.bbox_point is None:
        self.bbox_point = None
      if self.lwh is None:
        self.lwh = geometry_msgs.msg.Vector3()
      end = 0
      self.bbox_point = []
      for i in range(0, 8):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.bbox_point.append(val1)
      _x = self
      start = end
      end += 48
      (_x.lwh.x, _x.lwh.y, _x.lwh.z, _x.x_pos, _x.y_pos, _x.z_pos, _x.lidar_x_pos, _x.lidar_y_pos, _x.lidar_z_pos,) = _get_struct_3d6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3d6f = None
def _get_struct_3d6f():
    global _struct_3d6f
    if _struct_3d6f is None:
        _struct_3d6f = struct.Struct("<3d6f")
    return _struct_3d6f
