
(cl:in-package :asdf)

(defsystem "custom_msgs-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils )
  :components ((:file "_package")
    (:file "BrakeLightCmd" :depends-on ("_package_BrakeLightCmd"))
    (:file "_package_BrakeLightCmd" :depends-on ("_package"))
    (:file "DoorCmd" :depends-on ("_package_DoorCmd"))
    (:file "_package_DoorCmd" :depends-on ("_package"))
    (:file "EPBCmd" :depends-on ("_package_EPBCmd"))
    (:file "_package_EPBCmd" :depends-on ("_package"))
    (:file "FogLampCmd" :depends-on ("_package_FogLampCmd"))
    (:file "_package_FogLampCmd" :depends-on ("_package"))
    (:file "HornsCmd" :depends-on ("_package_HornsCmd"))
    (:file "_package_HornsCmd" :depends-on ("_package"))
    (:file "LKSStatusCmd" :depends-on ("_package_LKSStatusCmd"))
    (:file "_package_LKSStatusCmd" :depends-on ("_package"))
    (:file "SideLampsCmd" :depends-on ("_package_SideLampsCmd"))
    (:file "_package_SideLampsCmd" :depends-on ("_package"))
    (:file "TurnLightCmd" :depends-on ("_package_TurnLightCmd"))
    (:file "_package_TurnLightCmd" :depends-on ("_package"))
    (:file "WindowCmd" :depends-on ("_package_WindowCmd"))
    (:file "_package_WindowCmd" :depends-on ("_package"))
    (:file "WipersCmd" :depends-on ("_package_WipersCmd"))
    (:file "_package_WipersCmd" :depends-on ("_package"))
  ))