// Generated by gencpp from file custom_msgs/AEB.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_AEB_H
#define CUSTOM_MSGS_MESSAGE_AEB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct AEB_
{
  typedef AEB_<ContainerAllocator> Type;

  AEB_()
    : do_aeb(false)
    , dist(0.0)  {
    }
  AEB_(const ContainerAllocator& _alloc)
    : do_aeb(false)
    , dist(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _do_aeb_type;
  _do_aeb_type do_aeb;

   typedef float _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::custom_msgs::AEB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::AEB_<ContainerAllocator> const> ConstPtr;

}; // struct AEB_

typedef ::custom_msgs::AEB_<std::allocator<void> > AEB;

typedef boost::shared_ptr< ::custom_msgs::AEB > AEBPtr;
typedef boost::shared_ptr< ::custom_msgs::AEB const> AEBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::AEB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::AEB_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::AEB_<ContainerAllocator1> & lhs, const ::custom_msgs::AEB_<ContainerAllocator2> & rhs)
{
  return lhs.do_aeb == rhs.do_aeb &&
    lhs.dist == rhs.dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::AEB_<ContainerAllocator1> & lhs, const ::custom_msgs::AEB_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::AEB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::AEB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::AEB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::AEB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::AEB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::AEB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::AEB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cd562658145415c7ce4f97d390f01cb";
  }

  static const char* value(const ::custom_msgs::AEB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cd562658145415cULL;
  static const uint64_t static_value2 = 0x7ce4f97d390f01cbULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::AEB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/AEB";
  }

  static const char* value(const ::custom_msgs::AEB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::AEB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool    do_aeb #是否执行AEB\n"
"float32 dist   #目标距离\n"
;
  }

  static const char* value(const ::custom_msgs::AEB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::AEB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.do_aeb);
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AEB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::AEB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::AEB_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "do_aeb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.do_aeb);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_AEB_H
