// Generated by gencpp from file custom_msgs/AmbulanceResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_AMBULANCERESPONSE_H
#define CUSTOM_MSGS_MESSAGE_AMBULANCERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct AmbulanceResponse_
{
  typedef AmbulanceResponse_<ContainerAllocator> Type;

  AmbulanceResponse_()
    : IsAmbulance(false)  {
    }
  AmbulanceResponse_(const ContainerAllocator& _alloc)
    : IsAmbulance(false)  {
  (void)_alloc;
    }



   typedef uint8_t _IsAmbulance_type;
  _IsAmbulance_type IsAmbulance;





  typedef boost::shared_ptr< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AmbulanceResponse_

typedef ::custom_msgs::AmbulanceResponse_<std::allocator<void> > AmbulanceResponse;

typedef boost::shared_ptr< ::custom_msgs::AmbulanceResponse > AmbulanceResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::AmbulanceResponse const> AmbulanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::AmbulanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::AmbulanceResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::AmbulanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.IsAmbulance == rhs.IsAmbulance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::AmbulanceResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::AmbulanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2b9f78e4db8bc60eda8a99bc31095fc";
  }

  static const char* value(const ::custom_msgs::AmbulanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2b9f78e4db8bc60ULL;
  static const uint64_t static_value2 = 0xeda8a99bc31095fcULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/AmbulanceResponse";
  }

  static const char* value(const ::custom_msgs::AmbulanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool IsAmbulance          #是否有救护车 \n"
;
  }

  static const char* value(const ::custom_msgs::AmbulanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.IsAmbulance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AmbulanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::AmbulanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::AmbulanceResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "IsAmbulance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IsAmbulance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_AMBULANCERESPONSE_H
