// Generated by gencpp from file custom_msgs/App.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_APP_H
#define CUSTOM_MSGS_MESSAGE_APP_H

#include <ros/service_traits.h>


#include <custom_msgs/AppRequest.h>
#include <custom_msgs/AppResponse.h>


namespace custom_msgs
{

struct App
{

typedef AppRequest Request;
typedef AppResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct App
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::App > {
  static const char* value()
  {
    return "1d44dccf337b7714e82dab40e79d7373";
  }

  static const char* value(const ::custom_msgs::App&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::App > {
  static const char* value()
  {
    return "custom_msgs/App";
  }

  static const char* value(const ::custom_msgs::App&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::AppRequest> should match
// service_traits::MD5Sum< ::custom_msgs::App >
template<>
struct MD5Sum< ::custom_msgs::AppRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::App >::value();
  }
  static const char* value(const ::custom_msgs::AppRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::AppRequest> should match
// service_traits::DataType< ::custom_msgs::App >
template<>
struct DataType< ::custom_msgs::AppRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::App >::value();
  }
  static const char* value(const ::custom_msgs::AppRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::AppResponse> should match
// service_traits::MD5Sum< ::custom_msgs::App >
template<>
struct MD5Sum< ::custom_msgs::AppResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::App >::value();
  }
  static const char* value(const ::custom_msgs::AppResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::AppResponse> should match
// service_traits::DataType< ::custom_msgs::App >
template<>
struct DataType< ::custom_msgs::AppResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::App >::value();
  }
  static const char* value(const ::custom_msgs::AppResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_APP_H
