// Generated by gencpp from file custom_msgs/BrakeLightCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_BRAKELIGHTCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_BRAKELIGHTCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct BrakeLightCmdRequest_
{
  typedef BrakeLightCmdRequest_<ContainerAllocator> Type;

  BrakeLightCmdRequest_()
    : BrakeLightEnable(0)  {
    }
  BrakeLightCmdRequest_(const ContainerAllocator& _alloc)
    : BrakeLightEnable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _BrakeLightEnable_type;
  _BrakeLightEnable_type BrakeLightEnable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(BrakeOff)
  #undef BrakeOff
#endif
#if defined(_WIN32) && defined(BrakeOn)
  #undef BrakeOn
#endif

  enum {
    BrakeOff = 0u,
    BrakeOn = 1u,
  };


  typedef boost::shared_ptr< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeLightCmdRequest_

typedef ::custom_msgs::BrakeLightCmdRequest_<std::allocator<void> > BrakeLightCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::BrakeLightCmdRequest > BrakeLightCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::BrakeLightCmdRequest const> BrakeLightCmdRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.BrakeLightEnable == rhs.BrakeLightEnable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eafd24b09399fd926964747b5b09d214";
  }

  static const char* value(const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeafd24b09399fd92ULL;
  static const uint64_t static_value2 = 0x6964747b5b09d214ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/BrakeLightCmdRequest";
  }

  static const char* value(const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#      BCM LCM_LowLight  近光灯命令   0x0:TurnOff 0x1：Turn On；\n"
"#                                   0x2：Upanddown;0x3:Stop\n"
"#          LCM_HeadLight 远光灯命令  0x0:Turn Off;0x1:Turn On\n"
"#----------------------------------------------------------------\n"
"\n"
"#请求---------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 BrakeOff=0\n"
"uint8 BrakeOn=1\n"
"#控制字段\n"
"uint8 BrakeLightEnable\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BrakeLightEnable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeLightCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::BrakeLightCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "BrakeLightEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BrakeLightEnable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_BRAKELIGHTCMDREQUEST_H
