// Generated by gencpp from file custom_msgs/BrakeLightCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_BRAKELIGHTCMD_H
#define CUSTOM_MSGS_MESSAGE_BRAKELIGHTCMD_H

#include <ros/service_traits.h>


#include <custom_msgs/BrakeLightCmdRequest.h>
#include <custom_msgs/BrakeLightCmdResponse.h>


namespace custom_msgs
{

struct BrakeLightCmd
{

typedef BrakeLightCmdRequest Request;
typedef BrakeLightCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BrakeLightCmd
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::BrakeLightCmd > {
  static const char* value()
  {
    return "019a843542c6ec9330a3c43d4e701d28";
  }

  static const char* value(const ::custom_msgs::BrakeLightCmd&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::BrakeLightCmd > {
  static const char* value()
  {
    return "custom_msgs/BrakeLightCmd";
  }

  static const char* value(const ::custom_msgs::BrakeLightCmd&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::BrakeLightCmdRequest> should match
// service_traits::MD5Sum< ::custom_msgs::BrakeLightCmd >
template<>
struct MD5Sum< ::custom_msgs::BrakeLightCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::BrakeLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::BrakeLightCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::BrakeLightCmdRequest> should match
// service_traits::DataType< ::custom_msgs::BrakeLightCmd >
template<>
struct DataType< ::custom_msgs::BrakeLightCmdRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::BrakeLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::BrakeLightCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::BrakeLightCmdResponse> should match
// service_traits::MD5Sum< ::custom_msgs::BrakeLightCmd >
template<>
struct MD5Sum< ::custom_msgs::BrakeLightCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::BrakeLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::BrakeLightCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::BrakeLightCmdResponse> should match
// service_traits::DataType< ::custom_msgs::BrakeLightCmd >
template<>
struct DataType< ::custom_msgs::BrakeLightCmdResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::BrakeLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::BrakeLightCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_BRAKELIGHTCMD_H
