// Generated by gencpp from file custom_msgs/ControlRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CONTROLREQUEST_H
#define CUSTOM_MSGS_MESSAGE_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ControlRequest_
{
  typedef ControlRequest_<ContainerAllocator> Type;

  ControlRequest_()
    : type(0)
    , enable(false)
    , info(0.0)
    , source()  {
    }
  ControlRequest_(const ContainerAllocator& _alloc)
    : type(0)
    , enable(false)
    , info(0.0)
    , source(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _enable_type;
  _enable_type enable;

   typedef float _info_type;
  _info_type info;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(Is_stop)
  #undef Is_stop
#endif
#if defined(_WIN32) && defined(Is_aeb)
  #undef Is_aeb
#endif
#if defined(_WIN32) && defined(Is_back)
  #undef Is_back
#endif
#if defined(_WIN32) && defined(Is_switch_speed)
  #undef Is_switch_speed
#endif

  enum {
    Is_stop = 1u,
    Is_aeb = 2u,
    Is_back = 3u,
    Is_switch_speed = 4u,
  };


  typedef boost::shared_ptr< ::custom_msgs::ControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlRequest_

typedef ::custom_msgs::ControlRequest_<std::allocator<void> > ControlRequest;

typedef boost::shared_ptr< ::custom_msgs::ControlRequest > ControlRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::ControlRequest const> ControlRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ControlRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::ControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.enable == rhs.enable &&
    lhs.info == rhs.info &&
    lhs.source == rhs.source;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ControlRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::ControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35e8d4ea6c1ae1ec1c75741c61fa2a4d";
  }

  static const char* value(const ::custom_msgs::ControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35e8d4ea6c1ae1ecULL;
  static const uint64_t static_value2 = 0x1c75741c61fa2a4dULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ControlRequest";
  }

  static const char* value(const ::custom_msgs::ControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#横向规划\n"
"#------------------------------\n"
"\n"
"uint8    Is_stop = 1\n"
"uint8    Is_aeb  = 2\n"
"uint8    Is_back = 3\n"
"uint8    Is_switch_speed = 4\n"
"\n"
"uint8   type     #控制类别\n"
"bool    enable   #使能\n"
"float32 info     #包括速度、刹车距离\n"
"string  source   #控制消息来源\n"
;
  }

  static const char* value(const ::custom_msgs::ControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.enable);
      stream.next(m.info);
      stream.next(m.source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ControlRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "info: ";
    Printer<float>::stream(s, indent + "  ", v.info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CONTROLREQUEST_H
