// Generated by gencpp from file custom_msgs/Control.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CONTROL_H
#define CUSTOM_MSGS_MESSAGE_CONTROL_H

#include <ros/service_traits.h>


#include <custom_msgs/ControlRequest.h>
#include <custom_msgs/ControlResponse.h>


namespace custom_msgs
{

struct Control
{

typedef ControlRequest Request;
typedef ControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Control
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::Control > {
  static const char* value()
  {
    return "381944d60ba0e70fd89c5bcfc7b6474d";
  }

  static const char* value(const ::custom_msgs::Control&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::Control > {
  static const char* value()
  {
    return "custom_msgs/Control";
  }

  static const char* value(const ::custom_msgs::Control&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::ControlRequest> should match
// service_traits::MD5Sum< ::custom_msgs::Control >
template<>
struct MD5Sum< ::custom_msgs::ControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Control >::value();
  }
  static const char* value(const ::custom_msgs::ControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ControlRequest> should match
// service_traits::DataType< ::custom_msgs::Control >
template<>
struct DataType< ::custom_msgs::ControlRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Control >::value();
  }
  static const char* value(const ::custom_msgs::ControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::ControlResponse> should match
// service_traits::MD5Sum< ::custom_msgs::Control >
template<>
struct MD5Sum< ::custom_msgs::ControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Control >::value();
  }
  static const char* value(const ::custom_msgs::ControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ControlResponse> should match
// service_traits::DataType< ::custom_msgs::Control >
template<>
struct DataType< ::custom_msgs::ControlResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Control >::value();
  }
  static const char* value(const ::custom_msgs::ControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CONTROL_H
