// Generated by gencpp from file custom_msgs/ControlMode.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CONTROLMODE_H
#define CUSTOM_MSGS_MESSAGE_CONTROLMODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ControlMode_
{
  typedef ControlMode_<ContainerAllocator> Type;

  ControlMode_()
    : start(0)
    , mode_type(0)
    , brake_enable(0)
    , brake_value(0)
    , speed_require(0.0)
    , angle_require(0.0)  {
    }
  ControlMode_(const ContainerAllocator& _alloc)
    : start(0)
    , mode_type(0)
    , brake_enable(0)
    , brake_value(0)
    , speed_require(0.0)
    , angle_require(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;

   typedef uint8_t _mode_type_type;
  _mode_type_type mode_type;

   typedef uint8_t _brake_enable_type;
  _brake_enable_type brake_enable;

   typedef uint8_t _brake_value_type;
  _brake_value_type brake_value;

   typedef float _speed_require_type;
  _speed_require_type speed_require;

   typedef float _angle_require_type;
  _angle_require_type angle_require;





  typedef boost::shared_ptr< ::custom_msgs::ControlMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ControlMode_<ContainerAllocator> const> ConstPtr;

}; // struct ControlMode_

typedef ::custom_msgs::ControlMode_<std::allocator<void> > ControlMode;

typedef boost::shared_ptr< ::custom_msgs::ControlMode > ControlModePtr;
typedef boost::shared_ptr< ::custom_msgs::ControlMode const> ControlModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ControlMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ControlMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ControlMode_<ContainerAllocator1> & lhs, const ::custom_msgs::ControlMode_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.mode_type == rhs.mode_type &&
    lhs.brake_enable == rhs.brake_enable &&
    lhs.brake_value == rhs.brake_value &&
    lhs.speed_require == rhs.speed_require &&
    lhs.angle_require == rhs.angle_require;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ControlMode_<ContainerAllocator1> & lhs, const ::custom_msgs::ControlMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ControlMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ControlMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ControlMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ControlMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ControlMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ControlMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c547e8f4a6c7926cc11dc380930bfb6";
  }

  static const char* value(const ::custom_msgs::ControlMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c547e8f4a6c7926ULL;
  static const uint64_t static_value2 = 0xcc11dc380930bfb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ControlMode";
  }

  static const char* value(const ::custom_msgs::ControlMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8      start                     #qidong\n"
"uint8      mode_type                 #模式类型  00：无， 自动模式：（11：自动生成地图，12：已有地图） 遥控模式：20\n"
"uint8      brake_enable              #制动使能  0：制动，1：可行驶\n"
"uint8      brake_value               #制动值  \n"
"float32    speed_require             #速度要求\n"
"float32    angle_require             #角度要求\n"
;
  }

  static const char* value(const ::custom_msgs::ControlMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ControlMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.mode_type);
      stream.next(m.brake_enable);
      stream.next(m.brake_value);
      stream.next(m.speed_require);
      stream.next(m.angle_require);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ControlMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ControlMode_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "brake_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed_require: ";
    Printer<float>::stream(s, indent + "  ", v.speed_require);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_require: ";
    Printer<float>::stream(s, indent + "  ", v.angle_require);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CONTROLMODE_H
