// Generated by gencpp from file custom_msgs/CurPose.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CURPOSE_H
#define CUSTOM_MSGS_MESSAGE_CURPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct CurPose_
{
  typedef CurPose_<ContainerAllocator> Type;

  CurPose_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , s(0.0)
    , d(0.0)  {
    }
  CurPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , s(0.0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _s_type;
  _s_type s;

   typedef double _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::custom_msgs::CurPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::CurPose_<ContainerAllocator> const> ConstPtr;

}; // struct CurPose_

typedef ::custom_msgs::CurPose_<std::allocator<void> > CurPose;

typedef boost::shared_ptr< ::custom_msgs::CurPose > CurPosePtr;
typedef boost::shared_ptr< ::custom_msgs::CurPose const> CurPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::CurPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::CurPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::CurPose_<ContainerAllocator1> & lhs, const ::custom_msgs::CurPose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta &&
    lhs.s == rhs.s &&
    lhs.d == rhs.d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::CurPose_<ContainerAllocator1> & lhs, const ::custom_msgs::CurPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::CurPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::CurPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::CurPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::CurPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::CurPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::CurPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::CurPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e749843f9524582d302890cf564a4840";
  }

  static const char* value(const ::custom_msgs::CurPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe749843f9524582dULL;
  static const uint64_t static_value2 = 0x302890cf564a4840ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::CurPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/CurPose";
  }

  static const char* value(const ::custom_msgs::CurPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::CurPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：刘孟鑫\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"\n"
"float64                 x               #x位置\n"
"float64                 y               #y位置\n"
"float64                 theta           #航向\n"
"float64                 s               #s位置\n"
"float64                 d               #d位置\n"
;
  }

  static const char* value(const ::custom_msgs::CurPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::CurPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.s);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::CurPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::CurPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CURPOSE_H
