// Generated by gencpp from file custom_msgs/DoorCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_DOORCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_DOORCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct DoorCmdRequest_
{
  typedef DoorCmdRequest_<ContainerAllocator> Type;

  DoorCmdRequest_()
    : DoorLOCK(0)  {
    }
  DoorCmdRequest_(const ContainerAllocator& _alloc)
    : DoorLOCK(0)  {
  (void)_alloc;
    }



   typedef uint8_t _DoorLOCK_type;
  _DoorLOCK_type DoorLOCK;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NO_CMD)
  #undef NO_CMD
#endif
#if defined(_WIN32) && defined(UNLOCK_CMD)
  #undef UNLOCK_CMD
#endif
#if defined(_WIN32) && defined(LOCK_CMD)
  #undef LOCK_CMD
#endif

  enum {
    NO_CMD = 0u,
    UNLOCK_CMD = 6u,
    LOCK_CMD = 7u,
  };


  typedef boost::shared_ptr< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DoorCmdRequest_

typedef ::custom_msgs::DoorCmdRequest_<std::allocator<void> > DoorCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::DoorCmdRequest > DoorCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::DoorCmdRequest const> DoorCmdRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::DoorCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::DoorCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::DoorCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.DoorLOCK == rhs.DoorLOCK;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::DoorCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::DoorCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6fc2b585cc208c62e4c93679414bf232";
  }

  static const char* value(const ::custom_msgs::DoorCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6fc2b585cc208c62ULL;
  static const uint64_t static_value2 = 0xe4c93679414bf232ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/DoorCmdRequest";
  }

  static const char* value(const ::custom_msgs::DoorCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#      BCM BCM_Door 门锁控制\n"
"#         0x0  APA_NO_CMD\n"
"#         0x1  APA_UNLOCK_CMD\n"
"#         0x2  APA_LOCK_CMD\n"
"#----------------------------------------------------------------\n"
"\n"
"#请求------------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 NO_CMD=0\n"
"uint8 UNLOCK_CMD=6\n"
"uint8 LOCK_CMD=7\n"
"#控制字段\n"
"uint8 DoorLOCK\n"
"\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::DoorCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DoorLOCK);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoorCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::DoorCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::DoorCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "DoorLOCK: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.DoorLOCK);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DOORCMDREQUEST_H
