// Generated by gencpp from file custom_msgs/DoorCmdResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_DOORCMDRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_DOORCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct DoorCmdResponse_
{
  typedef DoorCmdResponse_<ContainerAllocator> Type;

  DoorCmdResponse_()
    : res(false)  {
    }
  DoorCmdResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DoorCmdResponse_

typedef ::custom_msgs::DoorCmdResponse_<std::allocator<void> > DoorCmdResponse;

typedef boost::shared_ptr< ::custom_msgs::DoorCmdResponse > DoorCmdResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::DoorCmdResponse const> DoorCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::DoorCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::DoorCmdResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::DoorCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::DoorCmdResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::DoorCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::custom_msgs::DoorCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/DoorCmdResponse";
  }

  static const char* value(const ::custom_msgs::DoorCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#返回值-----------------------------------------------------------\n"
"##定义赋值枚举\n"
"bool res\n"
"#控制字段\n"
"\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::DoorCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoorCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::DoorCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::DoorCmdResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_DOORCMDRESPONSE_H
