// Generated by gencpp from file custom_msgs/EPBCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_EPBCMD_H
#define CUSTOM_MSGS_MESSAGE_EPBCMD_H

#include <ros/service_traits.h>


#include <custom_msgs/EPBCmdRequest.h>
#include <custom_msgs/EPBCmdResponse.h>


namespace custom_msgs
{

struct EPBCmd
{

typedef EPBCmdRequest Request;
typedef EPBCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EPBCmd
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::EPBCmd > {
  static const char* value()
  {
    return "97ad02b260ada95bd0bdc9b9b400a370";
  }

  static const char* value(const ::custom_msgs::EPBCmd&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::EPBCmd > {
  static const char* value()
  {
    return "custom_msgs/EPBCmd";
  }

  static const char* value(const ::custom_msgs::EPBCmd&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::EPBCmdRequest> should match
// service_traits::MD5Sum< ::custom_msgs::EPBCmd >
template<>
struct MD5Sum< ::custom_msgs::EPBCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::EPBCmd >::value();
  }
  static const char* value(const ::custom_msgs::EPBCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::EPBCmdRequest> should match
// service_traits::DataType< ::custom_msgs::EPBCmd >
template<>
struct DataType< ::custom_msgs::EPBCmdRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::EPBCmd >::value();
  }
  static const char* value(const ::custom_msgs::EPBCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::EPBCmdResponse> should match
// service_traits::MD5Sum< ::custom_msgs::EPBCmd >
template<>
struct MD5Sum< ::custom_msgs::EPBCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::EPBCmd >::value();
  }
  static const char* value(const ::custom_msgs::EPBCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::EPBCmdResponse> should match
// service_traits::DataType< ::custom_msgs::EPBCmd >
template<>
struct DataType< ::custom_msgs::EPBCmdResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::EPBCmd >::value();
  }
  static const char* value(const ::custom_msgs::EPBCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_EPBCMD_H
