// Generated by gencpp from file custom_msgs/FogLampCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_FOGLAMPCMD_H
#define CUSTOM_MSGS_MESSAGE_FOGLAMPCMD_H

#include <ros/service_traits.h>


#include <custom_msgs/FogLampCmdRequest.h>
#include <custom_msgs/FogLampCmdResponse.h>


namespace custom_msgs
{

struct FogLampCmd
{

typedef FogLampCmdRequest Request;
typedef FogLampCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FogLampCmd
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::FogLampCmd > {
  static const char* value()
  {
    return "fbd437971ce67472818057cd942311e3";
  }

  static const char* value(const ::custom_msgs::FogLampCmd&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::FogLampCmd > {
  static const char* value()
  {
    return "custom_msgs/FogLampCmd";
  }

  static const char* value(const ::custom_msgs::FogLampCmd&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::FogLampCmdRequest> should match
// service_traits::MD5Sum< ::custom_msgs::FogLampCmd >
template<>
struct MD5Sum< ::custom_msgs::FogLampCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::FogLampCmd >::value();
  }
  static const char* value(const ::custom_msgs::FogLampCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::FogLampCmdRequest> should match
// service_traits::DataType< ::custom_msgs::FogLampCmd >
template<>
struct DataType< ::custom_msgs::FogLampCmdRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::FogLampCmd >::value();
  }
  static const char* value(const ::custom_msgs::FogLampCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::FogLampCmdResponse> should match
// service_traits::MD5Sum< ::custom_msgs::FogLampCmd >
template<>
struct MD5Sum< ::custom_msgs::FogLampCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::FogLampCmd >::value();
  }
  static const char* value(const ::custom_msgs::FogLampCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::FogLampCmdResponse> should match
// service_traits::DataType< ::custom_msgs::FogLampCmd >
template<>
struct DataType< ::custom_msgs::FogLampCmdResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::FogLampCmd >::value();
  }
  static const char* value(const ::custom_msgs::FogLampCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_FOGLAMPCMD_H
