// Generated by gencpp from file custom_msgs/GateStat.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_GATESTAT_H
#define CUSTOM_MSGS_MESSAGE_GATESTAT_H

#include <ros/service_traits.h>


#include <custom_msgs/GateStatRequest.h>
#include <custom_msgs/GateStatResponse.h>


namespace custom_msgs
{

struct GateStat
{

typedef GateStatRequest Request;
typedef GateStatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GateStat
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::GateStat > {
  static const char* value()
  {
    return "15b8a5807c34c7a623d8c41ae0c40f7f";
  }

  static const char* value(const ::custom_msgs::GateStat&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::GateStat > {
  static const char* value()
  {
    return "custom_msgs/GateStat";
  }

  static const char* value(const ::custom_msgs::GateStat&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::GateStatRequest> should match
// service_traits::MD5Sum< ::custom_msgs::GateStat >
template<>
struct MD5Sum< ::custom_msgs::GateStatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::GateStat >::value();
  }
  static const char* value(const ::custom_msgs::GateStatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::GateStatRequest> should match
// service_traits::DataType< ::custom_msgs::GateStat >
template<>
struct DataType< ::custom_msgs::GateStatRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::GateStat >::value();
  }
  static const char* value(const ::custom_msgs::GateStatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::GateStatResponse> should match
// service_traits::MD5Sum< ::custom_msgs::GateStat >
template<>
struct MD5Sum< ::custom_msgs::GateStatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::GateStat >::value();
  }
  static const char* value(const ::custom_msgs::GateStatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::GateStatResponse> should match
// service_traits::DataType< ::custom_msgs::GateStat >
template<>
struct DataType< ::custom_msgs::GateStatResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::GateStat >::value();
  }
  static const char* value(const ::custom_msgs::GateStatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_GATESTAT_H
