// Generated by gencpp from file custom_msgs/HornsCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_HORNSCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_HORNSCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct HornsCmdRequest_
{
  typedef HornsCmdRequest_<ContainerAllocator> Type;

  HornsCmdRequest_()
    : HornsEnable(0)  {
    }
  HornsCmdRequest_(const ContainerAllocator& _alloc)
    : HornsEnable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _HornsEnable_type;
  _HornsEnable_type HornsEnable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TurnOff)
  #undef TurnOff
#endif
#if defined(_WIN32) && defined(TurnOn)
  #undef TurnOn
#endif

  enum {
    TurnOff = 0u,
    TurnOn = 1u,
  };


  typedef boost::shared_ptr< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HornsCmdRequest_

typedef ::custom_msgs::HornsCmdRequest_<std::allocator<void> > HornsCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::HornsCmdRequest > HornsCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::HornsCmdRequest const> HornsCmdRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::HornsCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::HornsCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::HornsCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.HornsEnable == rhs.HornsEnable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::HornsCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::HornsCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b666bceeb71670579cde71c6cca56130";
  }

  static const char* value(const ::custom_msgs::HornsCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb666bceeb7167057ULL;
  static const uint64_t static_value2 = 0x9cde71c6cca56130ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/HornsCmdRequest";
  }

  static const char* value(const ::custom_msgs::HornsCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#      BCM BCM_Horns 喇叭\n"
"#      0x0 :  Inactive； 0x1 :Active；\n"
"#----------------------------------------------------------------\n"
"\n"
"#请求---------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 TurnOff=0\n"
"uint8 TurnOn=1\n"
"\n"
"##请求控制量\n"
"uint8 HornsEnable\n"
"\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::HornsCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.HornsEnable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HornsCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::HornsCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::HornsCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "HornsEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.HornsEnable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_HORNSCMDREQUEST_H
