// Generated by gencpp from file custom_msgs/ImageObject.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_IMAGEOBJECT_H
#define CUSTOM_MSGS_MESSAGE_IMAGEOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct ImageObject_
{
  typedef ImageObject_<ContainerAllocator> Type;

  ImageObject_()
    : type(0)
    , lwh()
    , x_pos(0.0)
    , y_pos(0.0)  {
    }
  ImageObject_(const ContainerAllocator& _alloc)
    : type(0)
    , lwh(_alloc)
    , x_pos(0.0)
    , y_pos(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _lwh_type;
  _lwh_type lwh;

   typedef float _x_pos_type;
  _x_pos_type x_pos;

   typedef float _y_pos_type;
  _y_pos_type y_pos;





  typedef boost::shared_ptr< ::custom_msgs::ImageObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ImageObject_<ContainerAllocator> const> ConstPtr;

}; // struct ImageObject_

typedef ::custom_msgs::ImageObject_<std::allocator<void> > ImageObject;

typedef boost::shared_ptr< ::custom_msgs::ImageObject > ImageObjectPtr;
typedef boost::shared_ptr< ::custom_msgs::ImageObject const> ImageObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ImageObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ImageObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ImageObject_<ContainerAllocator1> & lhs, const ::custom_msgs::ImageObject_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.lwh == rhs.lwh &&
    lhs.x_pos == rhs.x_pos &&
    lhs.y_pos == rhs.y_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ImageObject_<ContainerAllocator1> & lhs, const ::custom_msgs::ImageObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImageObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImageObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImageObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImageObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImageObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImageObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ImageObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52fc8c35eac374a9f9e6b53e1bb99dc0";
  }

  static const char* value(const ::custom_msgs::ImageObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52fc8c35eac374a9ULL;
  static const uint64_t static_value2 = 0xf9e6b53e1bb99dc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ImageObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ImageObject";
  }

  static const char* value(const ::custom_msgs::ImageObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ImageObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#通过图像检测出的目标\n"
"#------------------------------\n"
"\n"
"int8        type                        #目标类型[待定]\n"
"\n"
"geometry_msgs/Vector3       lwh         #x,y,z分别为目标的长宽高，待定\n"
"float32     x_pos                       #x位置，待定\n"
"float32     y_pos                       #y位置，待定\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::ImageObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ImageObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.lwh);
      stream.next(m.x_pos);
      stream.next(m.y_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ImageObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ImageObject_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lwh: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.lwh);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_pos: ";
    Printer<float>::stream(s, indent + "  ", v.x_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_pos: ";
    Printer<float>::stream(s, indent + "  ", v.y_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_IMAGEOBJECT_H
