// Generated by gencpp from file custom_msgs/ImageDetect.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_IMAGEDETECT_H
#define CUSTOM_MSGS_MESSAGE_IMAGEDETECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ImageDetect_
{
  typedef ImageDetect_<ContainerAllocator> Type;

  ImageDetect_()
    : color(0)  {
    }
  ImageDetect_(const ContainerAllocator& _alloc)
    : color(0)  {
  (void)_alloc;
    }



   typedef int32_t _color_type;
  _color_type color;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INVALID)
  #undef INVALID
#endif
#if defined(_WIN32) && defined(RED)
  #undef RED
#endif
#if defined(_WIN32) && defined(GREEN)
  #undef GREEN
#endif
#if defined(_WIN32) && defined(YELLOW)
  #undef YELLOW
#endif

  enum {
    INVALID = 0,
    RED = 1,
    GREEN = 2,
    YELLOW = 3,
  };


  typedef boost::shared_ptr< ::custom_msgs::ImageDetect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ImageDetect_<ContainerAllocator> const> ConstPtr;

}; // struct ImageDetect_

typedef ::custom_msgs::ImageDetect_<std::allocator<void> > ImageDetect;

typedef boost::shared_ptr< ::custom_msgs::ImageDetect > ImageDetectPtr;
typedef boost::shared_ptr< ::custom_msgs::ImageDetect const> ImageDetectConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ImageDetect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ImageDetect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ImageDetect_<ContainerAllocator1> & lhs, const ::custom_msgs::ImageDetect_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ImageDetect_<ContainerAllocator1> & lhs, const ::custom_msgs::ImageDetect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImageDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ImageDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImageDetect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ImageDetect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImageDetect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ImageDetect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ImageDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed554179081ab2399c38deea6a52f088";
  }

  static const char* value(const ::custom_msgs::ImageDetect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed554179081ab239ULL;
  static const uint64_t static_value2 = 0x9c38deea6a52f088ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ImageDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ImageDetect";
  }

  static const char* value(const ::custom_msgs::ImageDetect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ImageDetect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 INVALID=0\n"
"int32 RED=1\n"
"int32 GREEN=2\n"
"int32 YELLOW=3\n"
"\n"
"int32 color \n"
;
  }

  static const char* value(const ::custom_msgs::ImageDetect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ImageDetect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageDetect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ImageDetect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ImageDetect_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_IMAGEDETECT_H
