// Generated by gencpp from file custom_msgs/LaneLine.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LANELINE_H
#define CUSTOM_MSGS_MESSAGE_LANELINE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct LaneLine_
{
  typedef LaneLine_<ContainerAllocator> Type;

  LaneLine_()
    : id(0)
    , type(0)
    , x()
    , y()
    , s()
    , points()
    , current_lane_num(0)  {
    }
  LaneLine_(const ContainerAllocator& _alloc)
    : id(0)
    , type(0)
    , x(_alloc)
    , y(_alloc)
    , s(_alloc)
    , points(_alloc)
    , current_lane_num(0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _type_type;
  _type_type type;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _x_type;
  _x_type x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_type;
  _y_type y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _s_type;
  _s_type s;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef uint8_t _current_lane_num_type;
  _current_lane_num_type current_lane_num;





  typedef boost::shared_ptr< ::custom_msgs::LaneLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::LaneLine_<ContainerAllocator> const> ConstPtr;

}; // struct LaneLine_

typedef ::custom_msgs::LaneLine_<std::allocator<void> > LaneLine;

typedef boost::shared_ptr< ::custom_msgs::LaneLine > LaneLinePtr;
typedef boost::shared_ptr< ::custom_msgs::LaneLine const> LaneLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::LaneLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::LaneLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::LaneLine_<ContainerAllocator1> & lhs, const ::custom_msgs::LaneLine_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.s == rhs.s &&
    lhs.points == rhs.points &&
    lhs.current_lane_num == rhs.current_lane_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::LaneLine_<ContainerAllocator1> & lhs, const ::custom_msgs::LaneLine_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LaneLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LaneLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LaneLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LaneLine_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LaneLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LaneLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::LaneLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3ebb5bbdb4203b7c30588c0e1e0db20";
  }

  static const char* value(const ::custom_msgs::LaneLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3ebb5bbdb4203b7ULL;
  static const uint64_t static_value2 = 0xc30588c0e1e0db20ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::LaneLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/LaneLine";
  }

  static const char* value(const ::custom_msgs::LaneLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::LaneLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#车道线\n"
"#------当前项目中车道线点序列长度为30\n"
"#------geometry_msgs/Point类型是（x,y,z),目前只填充x,y忽略z\n"
"#------------------------------\n"
"uint32                         id\n"
"uint8                          type\n"
"float64[]                      x\n"
"float64[]                      y\n"
"float64[]                      s\n"
"\n"
"geometry_msgs/Point[]          points\n"
"uint8                          current_lane_num\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::LaneLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::LaneLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.s);
      stream.next(m.points);
      stream.next(m.current_lane_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::LaneLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::LaneLine_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    if (v.x.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.x[i]);
    }
    if (v.x.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    if (v.y.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.y[i]);
    }
    if (v.y.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "s: ";
    if (v.s.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.s[i]);
    }
    if (v.s.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_lane_num: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_lane_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LANELINE_H
