// Generated by gencpp from file custom_msgs/LidarRawObjectArray.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LIDARRAWOBJECTARRAY_H
#define CUSTOM_MSGS_MESSAGE_LIDARRAWOBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msgs/LidarRawObject.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct LidarRawObjectArray_
{
  typedef LidarRawObjectArray_<ContainerAllocator> Type;

  LidarRawObjectArray_()
    : head()
    , objs()  {
    }
  LidarRawObjectArray_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , objs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef std::vector< ::custom_msgs::LidarRawObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::LidarRawObject_<ContainerAllocator> >> _objs_type;
  _objs_type objs;





  typedef boost::shared_ptr< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct LidarRawObjectArray_

typedef ::custom_msgs::LidarRawObjectArray_<std::allocator<void> > LidarRawObjectArray;

typedef boost::shared_ptr< ::custom_msgs::LidarRawObjectArray > LidarRawObjectArrayPtr;
typedef boost::shared_ptr< ::custom_msgs::LidarRawObjectArray const> LidarRawObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator1> & lhs, const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.objs == rhs.objs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator1> & lhs, const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91872448100bff9ab1fc1b93d510c0e4";
  }

  static const char* value(const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91872448100bff9aULL;
  static const uint64_t static_value2 = 0xb1fc1b93d510c0e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/LidarRawObjectArray";
  }

  static const char* value(const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#由激光雷达检测出的目标所组成的序列\n"
"#------------------------------\n"
"\n"
"std_msgs/Header head\n"
"\n"
"LidarRawObject[]    objs    #目标序列\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/LidarRawObject\n"
"#------------------------------\n"
"#通过激光雷达检测出的目标\n"
"#------------------------------\n"
"\n"
"\n"
"geometry_msgs/Point[8]    bbox_point  #目标边框的8个顶点\n"
"\n"
"\n"
"geometry_msgs/Vector3     lwh         #x,y,z分别为目标的长宽高，待定\n"
"float32                   x_pos       #x位置，待定\n"
"float32                   y_pos       #y位置，待定\n"
"float32                   z_pos       #\n"
"\n"
"float32                   lidar_x_pos       #储存雷达坐标，用于目标跟踪\n"
"float32                   lidar_y_pos       \n"
"float32                   lidar_z_pos\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.objs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarRawObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::LidarRawObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::LidarRawObjectArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objs: ";
    if (v.objs.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objs.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::custom_msgs::LidarRawObject_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objs[i]);
    }
    if (v.objs.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LIDARRAWOBJECTARRAY_H
