// Generated by gencpp from file custom_msgs/LinktrackNodeframe0.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LINKTRACKNODEFRAME0_H
#define CUSTOM_MSGS_MESSAGE_LINKTRACKNODEFRAME0_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/LinktrackNode0.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct LinktrackNodeframe0_
{
  typedef LinktrackNodeframe0_<ContainerAllocator> Type;

  LinktrackNodeframe0_()
    : role(0)
    , id(0)
    , nodes()  {
    }
  LinktrackNodeframe0_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , nodes(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector< ::custom_msgs::LinktrackNode0_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::LinktrackNode0_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNodeframe0_

typedef ::custom_msgs::LinktrackNodeframe0_<std::allocator<void> > LinktrackNodeframe0;

typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe0 > LinktrackNodeframe0Ptr;
typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe0 const> LinktrackNodeframe0ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator1> & lhs, const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator1> & lhs, const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99d2eee732fdf2fb898d64e9172d0e66";
  }

  static const char* value(const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99d2eee732fdf2fbULL;
  static const uint64_t static_value2 = 0x898d64e9172d0e66ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/LinktrackNodeframe0";
  }

  static const char* value(const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"LinktrackNode0[] nodes\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/LinktrackNode0\n"
"uint8 role\n"
"uint8 id\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNodeframe0_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::LinktrackNodeframe0_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nodes: ";
    if (v.nodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::custom_msgs::LinktrackNode0_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.nodes[i]);
    }
    if (v.nodes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LINKTRACKNODEFRAME0_H
