// Generated by gencpp from file custom_msgs/LinktrackNodeframe1.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LINKTRACKNODEFRAME1_H
#define CUSTOM_MSGS_MESSAGE_LINKTRACKNODEFRAME1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/LinktrackNode1.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct LinktrackNodeframe1_
{
  typedef LinktrackNodeframe1_<ContainerAllocator> Type;

  LinktrackNodeframe1_()
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , voltage(0.0)
    , nodes()  {
    }
  LinktrackNodeframe1_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , voltage(0.0)
    , nodes(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint32_t _local_time_type;
  _local_time_type local_time;

   typedef uint32_t _system_time_type;
  _system_time_type system_time;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef std::vector< ::custom_msgs::LinktrackNode1_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::LinktrackNode1_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNodeframe1_

typedef ::custom_msgs::LinktrackNodeframe1_<std::allocator<void> > LinktrackNodeframe1;

typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe1 > LinktrackNodeframe1Ptr;
typedef boost::shared_ptr< ::custom_msgs::LinktrackNodeframe1 const> LinktrackNodeframe1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator1> & lhs, const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.local_time == rhs.local_time &&
    lhs.system_time == rhs.system_time &&
    lhs.voltage == rhs.voltage &&
    lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator1> & lhs, const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a522663cdf935548d202960a37f14ce";
  }

  static const char* value(const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a522663cdf93554ULL;
  static const uint64_t static_value2 = 0x8d202960a37f14ceULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/LinktrackNodeframe1";
  }

  static const char* value(const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"uint32 local_time\n"
"uint32 system_time\n"
"float32 voltage\n"
"LinktrackNode1[] nodes\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/LinktrackNode1\n"
"uint8 role\n"
"uint8 id\n"
"float32[3] pos_3d\n"
;
  }

  static const char* value(const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.local_time);
      stream.next(m.system_time);
      stream.next(m.voltage);
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNodeframe1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::LinktrackNodeframe1_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "local_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.local_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "system_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.system_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nodes: ";
    if (v.nodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::custom_msgs::LinktrackNode1_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.nodes[i]);
    }
    if (v.nodes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LINKTRACKNODEFRAME1_H
