// Generated by gencpp from file custom_msgs/LKSStatusCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_LKSSTATUSCMD_H
#define CUSTOM_MSGS_MESSAGE_LKSSTATUSCMD_H

#include <ros/service_traits.h>


#include <custom_msgs/LKSStatusCmdRequest.h>
#include <custom_msgs/LKSStatusCmdResponse.h>


namespace custom_msgs
{

struct LKSStatusCmd
{

typedef LKSStatusCmdRequest Request;
typedef LKSStatusCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LKSStatusCmd
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::LKSStatusCmd > {
  static const char* value()
  {
    return "7bb5f6915f70508cfdaad8cf055e8ba8";
  }

  static const char* value(const ::custom_msgs::LKSStatusCmd&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::LKSStatusCmd > {
  static const char* value()
  {
    return "custom_msgs/LKSStatusCmd";
  }

  static const char* value(const ::custom_msgs::LKSStatusCmd&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::LKSStatusCmdRequest> should match
// service_traits::MD5Sum< ::custom_msgs::LKSStatusCmd >
template<>
struct MD5Sum< ::custom_msgs::LKSStatusCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::LKSStatusCmd >::value();
  }
  static const char* value(const ::custom_msgs::LKSStatusCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::LKSStatusCmdRequest> should match
// service_traits::DataType< ::custom_msgs::LKSStatusCmd >
template<>
struct DataType< ::custom_msgs::LKSStatusCmdRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::LKSStatusCmd >::value();
  }
  static const char* value(const ::custom_msgs::LKSStatusCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::LKSStatusCmdResponse> should match
// service_traits::MD5Sum< ::custom_msgs::LKSStatusCmd >
template<>
struct MD5Sum< ::custom_msgs::LKSStatusCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::LKSStatusCmd >::value();
  }
  static const char* value(const ::custom_msgs::LKSStatusCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::LKSStatusCmdResponse> should match
// service_traits::DataType< ::custom_msgs::LKSStatusCmd >
template<>
struct DataType< ::custom_msgs::LKSStatusCmdResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::LKSStatusCmd >::value();
  }
  static const char* value(const ::custom_msgs::LKSStatusCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_LKSSTATUSCMD_H
