// Generated by gencpp from file custom_msgs/Map_Switch.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_MAP_SWITCH_H
#define CUSTOM_MSGS_MESSAGE_MAP_SWITCH_H

#include <ros/service_traits.h>


#include <custom_msgs/Map_SwitchRequest.h>
#include <custom_msgs/Map_SwitchResponse.h>


namespace custom_msgs
{

struct Map_Switch
{

typedef Map_SwitchRequest Request;
typedef Map_SwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Map_Switch
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::Map_Switch > {
  static const char* value()
  {
    return "6e0c418adb888dd8625f58056e1e3cec";
  }

  static const char* value(const ::custom_msgs::Map_Switch&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::Map_Switch > {
  static const char* value()
  {
    return "custom_msgs/Map_Switch";
  }

  static const char* value(const ::custom_msgs::Map_Switch&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::Map_SwitchRequest> should match
// service_traits::MD5Sum< ::custom_msgs::Map_Switch >
template<>
struct MD5Sum< ::custom_msgs::Map_SwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Map_Switch >::value();
  }
  static const char* value(const ::custom_msgs::Map_SwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::Map_SwitchRequest> should match
// service_traits::DataType< ::custom_msgs::Map_Switch >
template<>
struct DataType< ::custom_msgs::Map_SwitchRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Map_Switch >::value();
  }
  static const char* value(const ::custom_msgs::Map_SwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::Map_SwitchResponse> should match
// service_traits::MD5Sum< ::custom_msgs::Map_Switch >
template<>
struct MD5Sum< ::custom_msgs::Map_SwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Map_Switch >::value();
  }
  static const char* value(const ::custom_msgs::Map_SwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::Map_SwitchResponse> should match
// service_traits::DataType< ::custom_msgs::Map_Switch >
template<>
struct DataType< ::custom_msgs::Map_SwitchResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Map_Switch >::value();
  }
  static const char* value(const ::custom_msgs::Map_SwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_MAP_SWITCH_H
