// Generated by gencpp from file custom_msgs/NaviData.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_NAVIDATA_H
#define CUSTOM_MSGS_MESSAGE_NAVIDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct NaviData_
{
  typedef NaviData_<ContainerAllocator> Type;

  NaviData_()
    : head()
    , pitch(0.0)
    , roll(0.0)
    , heading(0.0)
    , longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)
    , speed2d(0.0)
    , Ve(0.0)
    , Vn(0.0)
    , Vu(0.0)
    , pose_type(0)
    , gpsTime(0.0)
    , INS_Status(0)
    , Lat_vari(0.0)
    , Lon_vari(0.0)  {
    }
  NaviData_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , pitch(0.0)
    , roll(0.0)
    , heading(0.0)
    , longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)
    , speed2d(0.0)
    , Ve(0.0)
    , Vn(0.0)
    , Vu(0.0)
    , pose_type(0)
    , gpsTime(0.0)
    , INS_Status(0)
    , Lat_vari(0.0)
    , Lon_vari(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _heading_type;
  _heading_type heading;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef float _speed2d_type;
  _speed2d_type speed2d;

   typedef float _Ve_type;
  _Ve_type Ve;

   typedef float _Vn_type;
  _Vn_type Vn;

   typedef float _Vu_type;
  _Vu_type Vu;

   typedef int32_t _pose_type_type;
  _pose_type_type pose_type;

   typedef double _gpsTime_type;
  _gpsTime_type gpsTime;

   typedef int32_t _INS_Status_type;
  _INS_Status_type INS_Status;

   typedef float _Lat_vari_type;
  _Lat_vari_type Lat_vari;

   typedef float _Lon_vari_type;
  _Lon_vari_type Lon_vari;





  typedef boost::shared_ptr< ::custom_msgs::NaviData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::NaviData_<ContainerAllocator> const> ConstPtr;

}; // struct NaviData_

typedef ::custom_msgs::NaviData_<std::allocator<void> > NaviData;

typedef boost::shared_ptr< ::custom_msgs::NaviData > NaviDataPtr;
typedef boost::shared_ptr< ::custom_msgs::NaviData const> NaviDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::NaviData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::NaviData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::NaviData_<ContainerAllocator1> & lhs, const ::custom_msgs::NaviData_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.heading == rhs.heading &&
    lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude &&
    lhs.altitude == rhs.altitude &&
    lhs.speed2d == rhs.speed2d &&
    lhs.Ve == rhs.Ve &&
    lhs.Vn == rhs.Vn &&
    lhs.Vu == rhs.Vu &&
    lhs.pose_type == rhs.pose_type &&
    lhs.gpsTime == rhs.gpsTime &&
    lhs.INS_Status == rhs.INS_Status &&
    lhs.Lat_vari == rhs.Lat_vari &&
    lhs.Lon_vari == rhs.Lon_vari;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::NaviData_<ContainerAllocator1> & lhs, const ::custom_msgs::NaviData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::NaviData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::NaviData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::NaviData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::NaviData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::NaviData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::NaviData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::NaviData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bf1fc8c7c8a4b0662c1e912fa5e0615";
  }

  static const char* value(const ::custom_msgs::NaviData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bf1fc8c7c8a4b06ULL;
  static const uint64_t static_value2 = 0x62c1e912fa5e0615ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::NaviData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/NaviData";
  }

  static const char* value(const ::custom_msgs::NaviData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::NaviData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------------------------------------\n"
"#导航信息\n"
"#来源于GNSS，INS设备\n"
"\n"
"# 50 NARROW_INT Integer narrow-lane ambiguity solution\n"
"# 56 INS_RTKFIXED INS RTK fixed ambiguities solution\n"
"# 51 RTK_DIRECT_INS RTK status where the RTK filter is directly initialized from the INS filter\n"
"# 55 INS_RTKFLOAT INS RTK floating point ambiguities solution\n"
"# 52 INS_SBAS INS calculated position corrected for the antenna\n"
"# 54 INS_PSRDIFF INS pseudorange differential solution\n"
"# 53 INS_PSRSP INS pseudorange single point solution – no DGPS corrections\n"
"#-----------------------------------------------------------------------------------------------\n"
"\n"
"\n"
"std_msgs/Header head\n"
"\n"
"float32 pitch          #俯仰角\n"
"float32 roll           #翻滚角\n"
"float32 heading        #航向角\n"
"\n"
"float64 longitude      #经度\n"
"float64 latitude       #纬度\n"
"float64 altitude       #海拔\n"
"\n"
"float32 speed2d        #车辆速度\n"
"# ----------------->\n"
"float32 Ve\n"
"\n"
"float32 Vn\n"
"\n"
"float32 Vu\n"
"\n"
"# <-----------------\n"
"\n"
"int32   pose_type      #定位状态\n"
"float64 gpsTime        #\n"
"\n"
"int32 INS_Status       #解算状态\n"
"float32 Lat_vari       #纬度标准差\n"
"float32 Lon_vari       #经度标准差\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::NaviData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::NaviData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.heading);
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.altitude);
      stream.next(m.speed2d);
      stream.next(m.Ve);
      stream.next(m.Vn);
      stream.next(m.Vu);
      stream.next(m.pose_type);
      stream.next(m.gpsTime);
      stream.next(m.INS_Status);
      stream.next(m.Lat_vari);
      stream.next(m.Lon_vari);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NaviData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::NaviData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::NaviData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed2d: ";
    Printer<float>::stream(s, indent + "  ", v.speed2d);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Ve: ";
    Printer<float>::stream(s, indent + "  ", v.Ve);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Vn: ";
    Printer<float>::stream(s, indent + "  ", v.Vn);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Vu: ";
    Printer<float>::stream(s, indent + "  ", v.Vu);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pose_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gpsTime: ";
    Printer<double>::stream(s, indent + "  ", v.gpsTime);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "INS_Status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.INS_Status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Lat_vari: ";
    Printer<float>::stream(s, indent + "  ", v.Lat_vari);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Lon_vari: ";
    Printer<float>::stream(s, indent + "  ", v.Lon_vari);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_NAVIDATA_H
