// Generated by gencpp from file custom_msgs/ObjectArray.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_OBJECTARRAY_H
#define CUSTOM_MSGS_MESSAGE_OBJECTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msgs/Object.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct ObjectArray_
{
  typedef ObjectArray_<ContainerAllocator> Type;

  ObjectArray_()
    : header()
    , objs()  {
    }
  ObjectArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::custom_msgs::Object_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::Object_<ContainerAllocator> >> _objs_type;
  _objs_type objs;





  typedef boost::shared_ptr< ::custom_msgs::ObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ObjectArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectArray_

typedef ::custom_msgs::ObjectArray_<std::allocator<void> > ObjectArray;

typedef boost::shared_ptr< ::custom_msgs::ObjectArray > ObjectArrayPtr;
typedef boost::shared_ptr< ::custom_msgs::ObjectArray const> ObjectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ObjectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ObjectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::custom_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objs == rhs.objs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ObjectArray_<ContainerAllocator1> & lhs, const ::custom_msgs::ObjectArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ObjectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ObjectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ObjectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ObjectArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d495b11e70f2d1f81d0ea8f651098c2e";
  }

  static const char* value(const ::custom_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd495b11e70f2d1f8ULL;
  static const uint64_t static_value2 = 0x1d0ea8f651098c2eULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ObjectArray";
  }

  static const char* value(const ::custom_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ObjectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#经过滤波后的目标序列\n"
"#------------------------------\n"
"\n"
"\n"
"std_msgs/Header     header\n"
"\n"
"Object[]         objs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/Object\n"
"#------------------------------\n"
"#经过滤波后的目标\n"
"#------------------------------\n"
"\n"
"\n"
"uint32      id                          #目标id\n"
"geometry_msgs/Point[8]    bbox_point    #目标边框的8个顶点\n"
"int8        type                        #目标类型[-1，unknown][1,car][2,pedestrian]\n"
"\n"
"float32     vx                          #x方向速度，m/s\n"
"float32     vy                          #y方向速度，m/s\n"
"float32     v                           #总速度，km/h\n"
"\n"
"\n"
"geometry_msgs/Vector3       lwh         #x,y,z分别为目标的长宽高,待定\n"
"float32     x_pos                       #x位置，待定\n"
"float32     y_pos                       #y位置，待定\n"
"\n"
"float32     s_pos                       #s位置\n"
"float32     d_pos                       #d位置\n"
"\n"
"float32     lidar_x_pos                 #储存雷达坐标，用于目标跟踪\n"
"float32     lidar_y_pos\n"
"float32     lidar_z_pos\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::ObjectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ObjectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ObjectArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objs: ";
    if (v.objs.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objs.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::custom_msgs::Object_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objs[i]);
    }
    if (v.objs.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_OBJECTARRAY_H
