// Generated by gencpp from file custom_msgs/Path.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_PATH_H
#define CUSTOM_MSGS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : x_ref()
    , y_ref()  {
    }
  Path_(const ContainerAllocator& _alloc)
    : x_ref(_alloc)
    , y_ref(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_ref_type;
  _x_ref_type x_ref;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_ref_type;
  _y_ref_type y_ref;





  typedef boost::shared_ptr< ::custom_msgs::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::custom_msgs::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::custom_msgs::Path > PathPtr;
typedef boost::shared_ptr< ::custom_msgs::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::Path_<ContainerAllocator1> & lhs, const ::custom_msgs::Path_<ContainerAllocator2> & rhs)
{
  return lhs.x_ref == rhs.x_ref &&
    lhs.y_ref == rhs.y_ref;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::Path_<ContainerAllocator1> & lhs, const ::custom_msgs::Path_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "086c82dabe09cb27a2918dd652bbdfdf";
  }

  static const char* value(const ::custom_msgs::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x086c82dabe09cb27ULL;
  static const uint64_t static_value2 = 0xa2918dd652bbdfdfULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/Path";
  }

  static const char* value(const ::custom_msgs::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#路径规划后所得到的路径点（x,y,v）\n"
"#------当前项目中路径点序列长度为30\n"
"#------------------------------\n"
"\n"
"float32[]           x_ref      #路径点的x坐标\n"
"float32[]           y_ref      #路径点的y坐标\n"
;
  }

  static const char* value(const ::custom_msgs::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_ref);
      stream.next(m.y_ref);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::Path_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x_ref: ";
    if (v.x_ref.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.x_ref.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.x_ref[i]);
    }
    if (v.x_ref.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_ref: ";
    if (v.y_ref.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.y_ref.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.y_ref[i]);
    }
    if (v.y_ref.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_PATH_H
