// Generated by gencpp from file custom_msgs/PRNDShiftCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_PRNDSHIFTCMD_H
#define CUSTOM_MSGS_MESSAGE_PRNDSHIFTCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct PRNDShiftCmd_
{
  typedef PRNDShiftCmd_<ContainerAllocator> Type;

  PRNDShiftCmd_()
    : head()
    , APA_TransPRNDShiftEnable(0)
    , APA_TransPRNDShiftReqValid(0)
    , APA_TransPRNDShiftRequest(0)  {
    }
  PRNDShiftCmd_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , APA_TransPRNDShiftEnable(0)
    , APA_TransPRNDShiftReqValid(0)
    , APA_TransPRNDShiftRequest(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef uint8_t _APA_TransPRNDShiftEnable_type;
  _APA_TransPRNDShiftEnable_type APA_TransPRNDShiftEnable;

   typedef uint8_t _APA_TransPRNDShiftReqValid_type;
  _APA_TransPRNDShiftReqValid_type APA_TransPRNDShiftReqValid;

   typedef uint8_t _APA_TransPRNDShiftRequest_type;
  _APA_TransPRNDShiftRequest_type APA_TransPRNDShiftRequest;





  typedef boost::shared_ptr< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> const> ConstPtr;

}; // struct PRNDShiftCmd_

typedef ::custom_msgs::PRNDShiftCmd_<std::allocator<void> > PRNDShiftCmd;

typedef boost::shared_ptr< ::custom_msgs::PRNDShiftCmd > PRNDShiftCmdPtr;
typedef boost::shared_ptr< ::custom_msgs::PRNDShiftCmd const> PRNDShiftCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator1> & lhs, const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.APA_TransPRNDShiftEnable == rhs.APA_TransPRNDShiftEnable &&
    lhs.APA_TransPRNDShiftReqValid == rhs.APA_TransPRNDShiftReqValid &&
    lhs.APA_TransPRNDShiftRequest == rhs.APA_TransPRNDShiftRequest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator1> & lhs, const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c04489b61cb0ba49e76093963fa7801";
  }

  static const char* value(const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c04489b61cb0ba4ULL;
  static const uint64_t static_value2 = 0x9e76093963fa7801ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/PRNDShiftCmd";
  }

  static const char* value(const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"\n"
"std_msgs/Header head\n"
"\n"
"uint8 APA_TransPRNDShiftEnable         #->>档位：请求换挡可控 0x1 disable able 0x1 Enable   ACM_APA Request Enable = 0x1:Control enabled\n"
"uint8 APA_TransPRNDShiftReqValid       #->>档位：换挡使能   0x0 = Invalid 0x1=Valid\n"
"uint8 APA_TransPRNDShiftRequest        #->>档位：换挡档位值 0x0=NoRequest;or 0x1=P ;or 0x2= R ; 0x3=N 0x4=D 0x5 :invalid\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.APA_TransPRNDShiftEnable);
      stream.next(m.APA_TransPRNDShiftReqValid);
      stream.next(m.APA_TransPRNDShiftRequest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PRNDShiftCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::PRNDShiftCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::PRNDShiftCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "APA_TransPRNDShiftEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.APA_TransPRNDShiftEnable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "APA_TransPRNDShiftReqValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.APA_TransPRNDShiftReqValid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "APA_TransPRNDShiftRequest: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.APA_TransPRNDShiftRequest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_PRNDSHIFTCMD_H
