// Generated by gencpp from file custom_msgs/Route.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_ROUTE_H
#define CUSTOM_MSGS_MESSAGE_ROUTE_H

#include <ros/service_traits.h>


#include <custom_msgs/RouteRequest.h>
#include <custom_msgs/RouteResponse.h>


namespace custom_msgs
{

struct Route
{

typedef RouteRequest Request;
typedef RouteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Route
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::Route > {
  static const char* value()
  {
    return "663e98081c7595a2a31a9cd17c6fa431";
  }

  static const char* value(const ::custom_msgs::Route&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::Route > {
  static const char* value()
  {
    return "custom_msgs/Route";
  }

  static const char* value(const ::custom_msgs::Route&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::RouteRequest> should match
// service_traits::MD5Sum< ::custom_msgs::Route >
template<>
struct MD5Sum< ::custom_msgs::RouteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Route >::value();
  }
  static const char* value(const ::custom_msgs::RouteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::RouteRequest> should match
// service_traits::DataType< ::custom_msgs::Route >
template<>
struct DataType< ::custom_msgs::RouteRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Route >::value();
  }
  static const char* value(const ::custom_msgs::RouteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::RouteResponse> should match
// service_traits::MD5Sum< ::custom_msgs::Route >
template<>
struct MD5Sum< ::custom_msgs::RouteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Route >::value();
  }
  static const char* value(const ::custom_msgs::RouteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::RouteResponse> should match
// service_traits::DataType< ::custom_msgs::Route >
template<>
struct DataType< ::custom_msgs::RouteResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Route >::value();
  }
  static const char* value(const ::custom_msgs::RouteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_ROUTE_H
