// Generated by gencpp from file custom_msgs/SideLampsCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_SIDELAMPSCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_SIDELAMPSCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct SideLampsCmdRequest_
{
  typedef SideLampsCmdRequest_<ContainerAllocator> Type;

  SideLampsCmdRequest_()
    : SideLampsEnable(0)  {
    }
  SideLampsCmdRequest_(const ContainerAllocator& _alloc)
    : SideLampsEnable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _SideLampsEnable_type;
  _SideLampsEnable_type SideLampsEnable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TurnOff)
  #undef TurnOff
#endif
#if defined(_WIN32) && defined(TurnOn)
  #undef TurnOn
#endif

  enum {
    TurnOff = 0u,
    TurnOn = 1u,
  };


  typedef boost::shared_ptr< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SideLampsCmdRequest_

typedef ::custom_msgs::SideLampsCmdRequest_<std::allocator<void> > SideLampsCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::SideLampsCmdRequest > SideLampsCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::SideLampsCmdRequest const> SideLampsCmdRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.SideLampsEnable == rhs.SideLampsEnable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371c358e104faf3d9945beaf0d2d1e3d";
  }

  static const char* value(const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371c358e104faf3dULL;
  static const uint64_t static_value2 = 0x9945beaf0d2d1e3dULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/SideLampsCmdRequest";
  }

  static const char* value(const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#----------------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#      LCM_SideLamps 示廓灯命令  0x0:Turn Off;0x1:Turn On\n"
"#----------------------------------------------------------------------\n"
"\n"
"#请求---------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 TurnOff=0\n"
"uint8 TurnOn=1\n"
"#\n"
"uint8 SideLampsEnable        #喇叭:0x0:Turn Off;0x1:Turn On\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SideLampsEnable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SideLampsCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::SideLampsCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "SideLampsEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SideLampsEnable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_SIDELAMPSCMDREQUEST_H
