// Generated by gencpp from file custom_msgs/SteeringCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_STEERINGCMD_H
#define CUSTOM_MSGS_MESSAGE_STEERINGCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct SteeringCmd_
{
  typedef SteeringCmd_<ContainerAllocator> Type;

  SteeringCmd_()
    : head()
    , SteeringAngle(0.0)  {
    }
  SteeringCmd_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , SteeringAngle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef float _SteeringAngle_type;
  _SteeringAngle_type SteeringAngle;





  typedef boost::shared_ptr< ::custom_msgs::SteeringCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::SteeringCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SteeringCmd_

typedef ::custom_msgs::SteeringCmd_<std::allocator<void> > SteeringCmd;

typedef boost::shared_ptr< ::custom_msgs::SteeringCmd > SteeringCmdPtr;
typedef boost::shared_ptr< ::custom_msgs::SteeringCmd const> SteeringCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::SteeringCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::SteeringCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::SteeringCmd_<ContainerAllocator1> & lhs, const ::custom_msgs::SteeringCmd_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.SteeringAngle == rhs.SteeringAngle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::SteeringCmd_<ContainerAllocator1> & lhs, const ::custom_msgs::SteeringCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::SteeringCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::SteeringCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::SteeringCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31999a5ef8b7f03fb56a72329494e3d5";
  }

  static const char* value(const ::custom_msgs::SteeringCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31999a5ef8b7f03fULL;
  static const uint64_t static_value2 = 0xb56a72329494e3d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/SteeringCmd";
  }

  static const char* value(const ::custom_msgs::SteeringCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"\n"
"std_msgs/Header head\n"
"\n"
"float32 SteeringAngle           #->>方向： 发送方向角度值\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::SteeringCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.SteeringAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteeringCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::SteeringCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::SteeringCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "SteeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.SteeringAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_STEERINGCMD_H
