// Generated by gencpp from file custom_msgs/TaskRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TASKREQUEST_H
#define CUSTOM_MSGS_MESSAGE_TASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct TaskRequest_
{
  typedef TaskRequest_<ContainerAllocator> Type;

  TaskRequest_()
    : task_type(0)
    , s_start(0.0)
    , s_end(0.0)
    , info(0.0)
    , info_2(0.0)  {
    }
  TaskRequest_(const ContainerAllocator& _alloc)
    : task_type(0)
    , s_start(0.0)
    , s_end(0.0)
    , info(0.0)
    , info_2(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _task_type_type;
  _task_type_type task_type;

   typedef double _s_start_type;
  _s_start_type s_start;

   typedef double _s_end_type;
  _s_end_type s_end;

   typedef double _info_type;
  _info_type info;

   typedef double _info_2_type;
  _info_2_type info_2;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(Task_Control)
  #undef Task_Control
#endif
#if defined(_WIN32) && defined(NewPathMission)
  #undef NewPathMission
#endif

  enum {
    Task_Control = 1u,
    NewPathMission = 2u,
  };


  typedef boost::shared_ptr< ::custom_msgs::TaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TaskRequest_

typedef ::custom_msgs::TaskRequest_<std::allocator<void> > TaskRequest;

typedef boost::shared_ptr< ::custom_msgs::TaskRequest > TaskRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::TaskRequest const> TaskRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TaskRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::TaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_type == rhs.task_type &&
    lhs.s_start == rhs.s_start &&
    lhs.s_end == rhs.s_end &&
    lhs.info == rhs.info &&
    lhs.info_2 == rhs.info_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TaskRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::TaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff2a8bc5438c15453ddc518e4924ac9b";
  }

  static const char* value(const ::custom_msgs::TaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff2a8bc5438c1545ULL;
  static const uint64_t static_value2 = 0x3ddc518e4924ac9bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TaskRequest";
  }

  static const char* value(const ::custom_msgs::TaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#任务请求\n"
"#------------------------------\n"
"uint8                   Task_Control        = 1    #农机作业任务\n"
"uint8                   NewPathMission      = 2    #避障任务操作\n"
"\n"
"uint8     task_type      #任务id\n"
"float64   s_start        #任务区间起始\n"
"float64   s_end          #任务区间结束\n"
"float64   info           #任务信息\n"
"float64   info_2         #任务信息2\n"
;
  }

  static const char* value(const ::custom_msgs::TaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_type);
      stream.next(m.s_start);
      stream.next(m.s_end);
      stream.next(m.info);
      stream.next(m.info_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TaskRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "s_start: ";
    Printer<double>::stream(s, indent + "  ", v.s_start);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "s_end: ";
    Printer<double>::stream(s, indent + "  ", v.s_end);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "info: ";
    Printer<double>::stream(s, indent + "  ", v.info);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "info_2: ";
    Printer<double>::stream(s, indent + "  ", v.info_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TASKREQUEST_H
