// Generated by gencpp from file custom_msgs/Task.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TASK_H
#define CUSTOM_MSGS_MESSAGE_TASK_H

#include <ros/service_traits.h>


#include <custom_msgs/TaskRequest.h>
#include <custom_msgs/TaskResponse.h>


namespace custom_msgs
{

struct Task
{

typedef TaskRequest Request;
typedef TaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::Task > {
  static const char* value()
  {
    return "bd2e6ee9570673e4c686fc680fef4544";
  }

  static const char* value(const ::custom_msgs::Task&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::Task > {
  static const char* value()
  {
    return "custom_msgs/Task";
  }

  static const char* value(const ::custom_msgs::Task&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::TaskRequest> should match
// service_traits::MD5Sum< ::custom_msgs::Task >
template<>
struct MD5Sum< ::custom_msgs::TaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Task >::value();
  }
  static const char* value(const ::custom_msgs::TaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::TaskRequest> should match
// service_traits::DataType< ::custom_msgs::Task >
template<>
struct DataType< ::custom_msgs::TaskRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Task >::value();
  }
  static const char* value(const ::custom_msgs::TaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::TaskResponse> should match
// service_traits::MD5Sum< ::custom_msgs::Task >
template<>
struct MD5Sum< ::custom_msgs::TaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Task >::value();
  }
  static const char* value(const ::custom_msgs::TaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::TaskResponse> should match
// service_traits::DataType< ::custom_msgs::Task >
template<>
struct DataType< ::custom_msgs::TaskResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Task >::value();
  }
  static const char* value(const ::custom_msgs::TaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TASK_H
