// Generated by gencpp from file custom_msgs/TaskResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TASKRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_TASKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct TaskResponse_
{
  typedef TaskResponse_<ContainerAllocator> Type;

  TaskResponse_()
    : isSuccess(false)  {
    }
  TaskResponse_(const ContainerAllocator& _alloc)
    : isSuccess(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isSuccess_type;
  _isSuccess_type isSuccess;





  typedef boost::shared_ptr< ::custom_msgs::TaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskResponse_

typedef ::custom_msgs::TaskResponse_<std::allocator<void> > TaskResponse;

typedef boost::shared_ptr< ::custom_msgs::TaskResponse > TaskResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::TaskResponse const> TaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TaskResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::TaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.isSuccess == rhs.isSuccess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TaskResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::TaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7dbd1de57ef8fd16c2d4ef28e12e701";
  }

  static const char* value(const ::custom_msgs::TaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7dbd1de57ef8fd1ULL;
  static const uint64_t static_value2 = 0x6c2d4ef28e12e701ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TaskResponse";
  }

  static const char* value(const ::custom_msgs::TaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isSuccess\n"
"\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::TaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isSuccess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TaskResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "isSuccess: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSuccess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TASKRESPONSE_H
