// Generated by gencpp from file custom_msgs/TofsenseCascade.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TOFSENSECASCADE_H
#define CUSTOM_MSGS_MESSAGE_TOFSENSECASCADE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msgs/TofsenseFrame0.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct TofsenseCascade_
{
  typedef TofsenseCascade_<ContainerAllocator> Type;

  TofsenseCascade_()
    : nodes()  {
    }
  TofsenseCascade_(const ContainerAllocator& _alloc)
    : nodes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::custom_msgs::TofsenseFrame0_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::TofsenseFrame0_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::custom_msgs::TofsenseCascade_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TofsenseCascade_<ContainerAllocator> const> ConstPtr;

}; // struct TofsenseCascade_

typedef ::custom_msgs::TofsenseCascade_<std::allocator<void> > TofsenseCascade;

typedef boost::shared_ptr< ::custom_msgs::TofsenseCascade > TofsenseCascadePtr;
typedef boost::shared_ptr< ::custom_msgs::TofsenseCascade const> TofsenseCascadeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TofsenseCascade_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TofsenseCascade_<ContainerAllocator1> & lhs, const ::custom_msgs::TofsenseCascade_<ContainerAllocator2> & rhs)
{
  return lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TofsenseCascade_<ContainerAllocator1> & lhs, const ::custom_msgs::TofsenseCascade_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TofsenseCascade_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TofsenseCascade_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TofsenseCascade_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f5a4318b44b44ec8258733a82bf1f6c";
  }

  static const char* value(const ::custom_msgs::TofsenseCascade_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f5a4318b44b44ecULL;
  static const uint64_t static_value2 = 0x8258733a82bf1f6cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TofsenseCascade";
  }

  static const char* value(const ::custom_msgs::TofsenseCascade_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TofsenseFrame0[] nodes\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/TofsenseFrame0\n"
"uint8 id\n"
"uint32 system_time\n"
"float32 dis\n"
"uint8 dis_status\n"
"uint16 signal_strength\n"
;
  }

  static const char* value(const ::custom_msgs::TofsenseCascade_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TofsenseCascade_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TofsenseCascade_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TofsenseCascade_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "nodes: ";
    if (v.nodes.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::custom_msgs::TofsenseFrame0_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.nodes[i]);
    }
    if (v.nodes.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TOFSENSECASCADE_H
