// Generated by gencpp from file custom_msgs/TrafficLightResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TRAFFICLIGHTRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_TRAFFICLIGHTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct TrafficLightResponse_
{
  typedef TrafficLightResponse_<ContainerAllocator> Type;

  TrafficLightResponse_()
    : color(0)
    , time(0)  {
    }
  TrafficLightResponse_(const ContainerAllocator& _alloc)
    : color(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef int32_t _color_type;
  _color_type color;

   typedef int32_t _time_type;
  _time_type time;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GREEN)
  #undef GREEN
#endif
#if defined(_WIN32) && defined(RED)
  #undef RED
#endif
#if defined(_WIN32) && defined(YELLOW)
  #undef YELLOW
#endif
#if defined(_WIN32) && defined(INVALID)
  #undef INVALID
#endif

  enum {
    GREEN = 2,
    RED = 1,
    YELLOW = 4,
    INVALID = 0,
  };


  typedef boost::shared_ptr< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightResponse_

typedef ::custom_msgs::TrafficLightResponse_<std::allocator<void> > TrafficLightResponse;

typedef boost::shared_ptr< ::custom_msgs::TrafficLightResponse > TrafficLightResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::TrafficLightResponse const> TrafficLightResponseConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TrafficLightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TrafficLightResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::TrafficLightResponse_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TrafficLightResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::TrafficLightResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19420091ef867fdd9e71b2541f1b6290";
  }

  static const char* value(const ::custom_msgs::TrafficLightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19420091ef867fddULL;
  static const uint64_t static_value2 = 0x9e71b2541f1b6290ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TrafficLightResponse";
  }

  static const char* value(const ::custom_msgs::TrafficLightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 GREEN=2\n"
"int32 RED=1\n"
"int32 YELLOW=4\n"
"int32 INVALID=0\n"
"\n"
"int32 color             # 1 red 2 green 3 黄色 -1无效\n"
"int32 time              # 剩余时间\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::TrafficLightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TrafficLightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TrafficLightResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TRAFFICLIGHTRESPONSE_H
