// Generated by gencpp from file custom_msgs/TrafficLightRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TRAFFICLIGHTREQUEST_H
#define CUSTOM_MSGS_MESSAGE_TRAFFICLIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct TrafficLightRequest_
{
  typedef TrafficLightRequest_<ContainerAllocator> Type;

  TrafficLightRequest_()
    : direction(0.0)
    , longitude(0.0)
    , latitude(0.0)  {
    }
  TrafficLightRequest_(const ContainerAllocator& _alloc)
    : direction(0.0)
    , longitude(0.0)
    , latitude(0.0)  {
  (void)_alloc;
    }



   typedef float _direction_type;
  _direction_type direction;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;





  typedef boost::shared_ptr< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightRequest_

typedef ::custom_msgs::TrafficLightRequest_<std::allocator<void> > TrafficLightRequest;

typedef boost::shared_ptr< ::custom_msgs::TrafficLightRequest > TrafficLightRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::TrafficLightRequest const> TrafficLightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TrafficLightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TrafficLightRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::TrafficLightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TrafficLightRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::TrafficLightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9939e047a88614d71388b60d21b4e1ad";
  }

  static const char* value(const ::custom_msgs::TrafficLightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9939e047a88614d7ULL;
  static const uint64_t static_value2 = 0x1388b60d21b4e1adULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TrafficLightRequest";
  }

  static const char* value(const ::custom_msgs::TrafficLightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#交通灯请求\n"
"#------------------------------\n"
"float32 direction       #车辆即将开往的方向，单位°，以车头为0，顺时针为正方向\n"
"float64 longitude       #交通灯所在路口中心的经度\n"
"float64 latitude        #交通灯所在路口中心的纬度\n"
;
  }

  static const char* value(const ::custom_msgs::TrafficLightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.longitude);
      stream.next(m.latitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TrafficLightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TrafficLightRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TRAFFICLIGHTREQUEST_H
