// Generated by gencpp from file custom_msgs/TrqBreCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TRQBRECMD_H
#define CUSTOM_MSGS_MESSAGE_TRQBRECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct TrqBreCmd_
{
  typedef TrqBreCmd_<ContainerAllocator> Type;

  TrqBreCmd_()
    : head()
    , trq_enable(0)
    , trq_value_2(0)
    , trq_value_3(0.0)
    , bre_enable(0)
    , bre_value(0.0)
    , ACC_DecToStop(0)
    , ACC_Driveoff(0)  {
    }
  TrqBreCmd_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , trq_enable(0)
    , trq_value_2(0)
    , trq_value_3(0.0)
    , bre_enable(0)
    , bre_value(0.0)
    , ACC_DecToStop(0)
    , ACC_Driveoff(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef uint8_t _trq_enable_type;
  _trq_enable_type trq_enable;

   typedef uint32_t _trq_value_2_type;
  _trq_value_2_type trq_value_2;

   typedef float _trq_value_3_type;
  _trq_value_3_type trq_value_3;

   typedef uint8_t _bre_enable_type;
  _bre_enable_type bre_enable;

   typedef float _bre_value_type;
  _bre_value_type bre_value;

   typedef uint8_t _ACC_DecToStop_type;
  _ACC_DecToStop_type ACC_DecToStop;

   typedef uint8_t _ACC_Driveoff_type;
  _ACC_Driveoff_type ACC_Driveoff;





  typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd_<ContainerAllocator> const> ConstPtr;

}; // struct TrqBreCmd_

typedef ::custom_msgs::TrqBreCmd_<std::allocator<void> > TrqBreCmd;

typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd > TrqBreCmdPtr;
typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd const> TrqBreCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TrqBreCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TrqBreCmd_<ContainerAllocator1> & lhs, const ::custom_msgs::TrqBreCmd_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.trq_enable == rhs.trq_enable &&
    lhs.trq_value_2 == rhs.trq_value_2 &&
    lhs.trq_value_3 == rhs.trq_value_3 &&
    lhs.bre_enable == rhs.bre_enable &&
    lhs.bre_value == rhs.bre_value &&
    lhs.ACC_DecToStop == rhs.ACC_DecToStop &&
    lhs.ACC_Driveoff == rhs.ACC_Driveoff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TrqBreCmd_<ContainerAllocator1> & lhs, const ::custom_msgs::TrqBreCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrqBreCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrqBreCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrqBreCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4c067bce3a4adbe38f794b306a03fb3";
  }

  static const char* value(const ::custom_msgs::TrqBreCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4c067bce3a4adbeULL;
  static const uint64_t static_value2 = 0x38f794b306a03fb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TrqBreCmd";
  }

  static const char* value(const ::custom_msgs::TrqBreCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"\n"
"std_msgs/Header head\n"
"\n"
"#float32 DeAccReq      \n"
"#float32 AccReq\n"
"#float32 SptReq\n"
"\n"
"uint8   trq_enable                    #发动机驱动扭矩是否使能\n"
"uint32  trq_value_2                   #->>扭矩:所需扭矩值     #2号车使用\n"
"float32 trq_value_3                   #->>扭矩:所需扭矩百分比  #3号车使用\n"
"uint8   bre_enable                    #刹车是否使能\n"
"float32 bre_value                     #刹车值\n"
"uint8   ACC_DecToStop                 #ACC请求减速到停止 0x0: no demand; 0x1: demand 车子按自己的减速度平滑停车 不受发送的其他指令控制\n"
"uint8   ACC_Driveoff                  #释放汽缸压力，必须与ACC_DecToStop配合使\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::TrqBreCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.trq_enable);
      stream.next(m.trq_value_2);
      stream.next(m.trq_value_3);
      stream.next(m.bre_enable);
      stream.next(m.bre_value);
      stream.next(m.ACC_DecToStop);
      stream.next(m.ACC_Driveoff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrqBreCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TrqBreCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TrqBreCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trq_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trq_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trq_value_2: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.trq_value_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "trq_value_3: ";
    Printer<float>::stream(s, indent + "  ", v.trq_value_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bre_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bre_enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bre_value: ";
    Printer<float>::stream(s, indent + "  ", v.bre_value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ACC_DecToStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ACC_DecToStop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ACC_Driveoff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ACC_Driveoff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TRQBRECMD_H
