// Generated by gencpp from file custom_msgs/TrqBreCmd485.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TRQBRECMD485_H
#define CUSTOM_MSGS_MESSAGE_TRQBRECMD485_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct TrqBreCmd485_
{
  typedef TrqBreCmd485_<ContainerAllocator> Type;

  TrqBreCmd485_()
    : head()
    , cmd_type(0)
    , pay_load(0)  {
    }
  TrqBreCmd485_(const ContainerAllocator& _alloc)
    : head(_alloc)
    , cmd_type(0)
    , pay_load(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef uint8_t _cmd_type_type;
  _cmd_type_type cmd_type;

   typedef uint8_t _pay_load_type;
  _pay_load_type pay_load;





  typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> const> ConstPtr;

}; // struct TrqBreCmd485_

typedef ::custom_msgs::TrqBreCmd485_<std::allocator<void> > TrqBreCmd485;

typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd485 > TrqBreCmd485Ptr;
typedef boost::shared_ptr< ::custom_msgs::TrqBreCmd485 const> TrqBreCmd485ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TrqBreCmd485_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TrqBreCmd485_<ContainerAllocator1> & lhs, const ::custom_msgs::TrqBreCmd485_<ContainerAllocator2> & rhs)
{
  return lhs.head == rhs.head &&
    lhs.cmd_type == rhs.cmd_type &&
    lhs.pay_load == rhs.pay_load;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TrqBreCmd485_<ContainerAllocator1> & lhs, const ::custom_msgs::TrqBreCmd485_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be77f276997429f5059b00917c72a649";
  }

  static const char* value(const ::custom_msgs::TrqBreCmd485_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe77f276997429f5ULL;
  static const uint64_t static_value2 = 0x059b00917c72a649ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TrqBreCmd485";
  }

  static const char* value(const ::custom_msgs::TrqBreCmd485_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"\n"
"std_msgs/Header head\n"
"\n"
"uint8   cmd_type                  #ming ling zi\n"
"uint8   pay_load                  #->>zai he: ming ling zi dui ying       \n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::TrqBreCmd485_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.head);
      stream.next(m.cmd_type);
      stream.next(m.pay_load);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrqBreCmd485_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TrqBreCmd485_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TrqBreCmd485_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "head: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cmd_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pay_load: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pay_load);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TRQBRECMD485_H
