// Generated by gencpp from file custom_msgs/TurnLightCmd.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TURNLIGHTCMD_H
#define CUSTOM_MSGS_MESSAGE_TURNLIGHTCMD_H

#include <ros/service_traits.h>


#include <custom_msgs/TurnLightCmdRequest.h>
#include <custom_msgs/TurnLightCmdResponse.h>


namespace custom_msgs
{

struct TurnLightCmd
{

typedef TurnLightCmdRequest Request;
typedef TurnLightCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurnLightCmd
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::TurnLightCmd > {
  static const char* value()
  {
    return "322d87667a5cf45a7b0e59fea7572bbf";
  }

  static const char* value(const ::custom_msgs::TurnLightCmd&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::TurnLightCmd > {
  static const char* value()
  {
    return "custom_msgs/TurnLightCmd";
  }

  static const char* value(const ::custom_msgs::TurnLightCmd&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::TurnLightCmdRequest> should match
// service_traits::MD5Sum< ::custom_msgs::TurnLightCmd >
template<>
struct MD5Sum< ::custom_msgs::TurnLightCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::TurnLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::TurnLightCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::TurnLightCmdRequest> should match
// service_traits::DataType< ::custom_msgs::TurnLightCmd >
template<>
struct DataType< ::custom_msgs::TurnLightCmdRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::TurnLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::TurnLightCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::TurnLightCmdResponse> should match
// service_traits::MD5Sum< ::custom_msgs::TurnLightCmd >
template<>
struct MD5Sum< ::custom_msgs::TurnLightCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::TurnLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::TurnLightCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::TurnLightCmdResponse> should match
// service_traits::DataType< ::custom_msgs::TurnLightCmd >
template<>
struct DataType< ::custom_msgs::TurnLightCmdResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::TurnLightCmd >::value();
  }
  static const char* value(const ::custom_msgs::TurnLightCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TURNLIGHTCMD_H
