// Generated by gencpp from file custom_msgs/TurnLightCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TURNLIGHTCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_TURNLIGHTCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct TurnLightCmdRequest_
{
  typedef TurnLightCmdRequest_<ContainerAllocator> Type;

  TurnLightCmdRequest_()
    : TurnLightEnable(0)  {
    }
  TurnLightCmdRequest_(const ContainerAllocator& _alloc)
    : TurnLightEnable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _TurnLightEnable_type;
  _TurnLightEnable_type TurnLightEnable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TurnOff)
  #undef TurnOff
#endif
#if defined(_WIN32) && defined(TurnLeft)
  #undef TurnLeft
#endif
#if defined(_WIN32) && defined(TurnRight)
  #undef TurnRight
#endif

  enum {
    TurnOff = 0u,
    TurnLeft = 1u,
    TurnRight = 2u,
  };


  typedef boost::shared_ptr< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurnLightCmdRequest_

typedef ::custom_msgs::TurnLightCmdRequest_<std::allocator<void> > TurnLightCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::TurnLightCmdRequest > TurnLightCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::TurnLightCmdRequest const> TurnLightCmdRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.TurnLightEnable == rhs.TurnLightEnable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fc1c961b0d1c465a6f2132e0974db96";
  }

  static const char* value(const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fc1c961b0d1c465ULL;
  static const uint64_t static_value2 = 0xa6f2132e0974db96ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TurnLightCmdRequest";
  }

  static const char* value(const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#----------------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#      LCM_TurnLight 转向灯命令  0x0:Not Active:0x1：\n"
"#                              TurnRight；0x2：TurnLeft;0x3:DoubleLight\n"
"#----------------------------------------------------------------------\n"
"\n"
"#请求---------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 TurnOff=0\n"
"uint8 TurnLeft=1\n"
"uint8 TurnRight=2\n"
"\n"
"#\n"
"uint8 TurnLightEnable\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TurnLightEnable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnLightCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TurnLightCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "TurnLightEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TurnLightEnable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TURNLIGHTCMDREQUEST_H
