// Generated by gencpp from file custom_msgs/VehicleStat.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_VEHICLESTAT_H
#define CUSTOM_MSGS_MESSAGE_VEHICLESTAT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct VehicleStat_
{
  typedef VehicleStat_<ContainerAllocator> Type;

  VehicleStat_()
    : VehicleSpeed(0.0)
    , GearShiftPositon(0)
    , ParkSts(0)
    , ErrorCode(0)
    , RemainingMile(0)
    , TolMileage(0.0)
    , SAS_SteeringAngle(0.0)
    , EMS_EngineSpeed(0.0)
    , EMS_EngineThrottlePosition(0.0)
    , EMS_AccPedal(0.0)
    , EMS_BrakePedalStatus(0)
    , TCU_GearShiftPositon(0)
    , VehicleModle(0)
    , veh_speed(0.0)
    , veh_longitude(0)
    , veh_latitude(0)
    , Drive_mode(0)
    , Vehicle_Top_height(0)  {
    }
  VehicleStat_(const ContainerAllocator& _alloc)
    : VehicleSpeed(0.0)
    , GearShiftPositon(0)
    , ParkSts(0)
    , ErrorCode(0)
    , RemainingMile(0)
    , TolMileage(0.0)
    , SAS_SteeringAngle(0.0)
    , EMS_EngineSpeed(0.0)
    , EMS_EngineThrottlePosition(0.0)
    , EMS_AccPedal(0.0)
    , EMS_BrakePedalStatus(0)
    , TCU_GearShiftPositon(0)
    , VehicleModle(0)
    , veh_speed(0.0)
    , veh_longitude(0)
    , veh_latitude(0)
    , Drive_mode(0)
    , Vehicle_Top_height(0)  {
  (void)_alloc;
    }



   typedef float _VehicleSpeed_type;
  _VehicleSpeed_type VehicleSpeed;

   typedef int8_t _GearShiftPositon_type;
  _GearShiftPositon_type GearShiftPositon;

   typedef uint8_t _ParkSts_type;
  _ParkSts_type ParkSts;

   typedef uint8_t _ErrorCode_type;
  _ErrorCode_type ErrorCode;

   typedef uint16_t _RemainingMile_type;
  _RemainingMile_type RemainingMile;

   typedef float _TolMileage_type;
  _TolMileage_type TolMileage;

   typedef float _SAS_SteeringAngle_type;
  _SAS_SteeringAngle_type SAS_SteeringAngle;

   typedef float _EMS_EngineSpeed_type;
  _EMS_EngineSpeed_type EMS_EngineSpeed;

   typedef float _EMS_EngineThrottlePosition_type;
  _EMS_EngineThrottlePosition_type EMS_EngineThrottlePosition;

   typedef float _EMS_AccPedal_type;
  _EMS_AccPedal_type EMS_AccPedal;

   typedef uint8_t _EMS_BrakePedalStatus_type;
  _EMS_BrakePedalStatus_type EMS_BrakePedalStatus;

   typedef uint8_t _TCU_GearShiftPositon_type;
  _TCU_GearShiftPositon_type TCU_GearShiftPositon;

   typedef uint8_t _VehicleModle_type;
  _VehicleModle_type VehicleModle;

   typedef float _veh_speed_type;
  _veh_speed_type veh_speed;

   typedef uint8_t _veh_longitude_type;
  _veh_longitude_type veh_longitude;

   typedef uint8_t _veh_latitude_type;
  _veh_latitude_type veh_latitude;

   typedef uint8_t _Drive_mode_type;
  _Drive_mode_type Drive_mode;

   typedef uint8_t _Vehicle_Top_height_type;
  _Vehicle_Top_height_type Vehicle_Top_height;





  typedef boost::shared_ptr< ::custom_msgs::VehicleStat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::VehicleStat_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleStat_

typedef ::custom_msgs::VehicleStat_<std::allocator<void> > VehicleStat;

typedef boost::shared_ptr< ::custom_msgs::VehicleStat > VehicleStatPtr;
typedef boost::shared_ptr< ::custom_msgs::VehicleStat const> VehicleStatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::VehicleStat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::VehicleStat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::VehicleStat_<ContainerAllocator1> & lhs, const ::custom_msgs::VehicleStat_<ContainerAllocator2> & rhs)
{
  return lhs.VehicleSpeed == rhs.VehicleSpeed &&
    lhs.GearShiftPositon == rhs.GearShiftPositon &&
    lhs.ParkSts == rhs.ParkSts &&
    lhs.ErrorCode == rhs.ErrorCode &&
    lhs.RemainingMile == rhs.RemainingMile &&
    lhs.TolMileage == rhs.TolMileage &&
    lhs.SAS_SteeringAngle == rhs.SAS_SteeringAngle &&
    lhs.EMS_EngineSpeed == rhs.EMS_EngineSpeed &&
    lhs.EMS_EngineThrottlePosition == rhs.EMS_EngineThrottlePosition &&
    lhs.EMS_AccPedal == rhs.EMS_AccPedal &&
    lhs.EMS_BrakePedalStatus == rhs.EMS_BrakePedalStatus &&
    lhs.TCU_GearShiftPositon == rhs.TCU_GearShiftPositon &&
    lhs.VehicleModle == rhs.VehicleModle &&
    lhs.veh_speed == rhs.veh_speed &&
    lhs.veh_longitude == rhs.veh_longitude &&
    lhs.veh_latitude == rhs.veh_latitude &&
    lhs.Drive_mode == rhs.Drive_mode &&
    lhs.Vehicle_Top_height == rhs.Vehicle_Top_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::VehicleStat_<ContainerAllocator1> & lhs, const ::custom_msgs::VehicleStat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::VehicleStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::VehicleStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::VehicleStat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::VehicleStat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::VehicleStat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::VehicleStat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::VehicleStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2bde6cd7946bf2902cdb4da11bc0391";
  }

  static const char* value(const ::custom_msgs::VehicleStat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2bde6cd7946bf29ULL;
  static const uint64_t static_value2 = 0x02cdb4da11bc0391ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::VehicleStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/VehicleStat";
  }

  static const char* value(const ::custom_msgs::VehicleStat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::VehicleStat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"float32   VehicleSpeed               #车速，单位km/h\n"
"int8      GearShiftPositon           #换挡器位置\n"
"uint8     ParkSts                    #驻车状态\n"
"#ErrorCode 各位为1代表含义如下：\n"
"#    0：不能收到can报文\n"
"#    1：VcuError不能进入自动驾驶状态\n"
"#    2：横向eps故障\n"
"#    3：纵向ebs故障\n"
"#    4：\n"
"#    5：\n"
"#    6：\n"
"#    7：\n"
"uint8 ErrorCode                      #故障码\n"
"uint16 RemainingMile                 #剩余里程计\n"
"float32 TolMileage                   #累计里程计\n"
"\n"
"float32 SAS_SteeringAngle               #方向盘转角速度\n"
"float32 EMS_EngineSpeed                 #发动机转速\n"
"float32 EMS_EngineThrottlePosition      #发动机节气门位置\n"
"float32 EMS_AccPedal                    #加速踏板位置\n"
"uint8   EMS_BrakePedalStatus            #制动踏板状态\n"
"uint8   TCU_GearShiftPositon            #换挡器位置\n"
"uint8   VehicleModle                    #车辆状态：自动驾驶or手动驾驶\n"
"\n"
"float32 veh_speed                       #速度，单位km/h\n"
"uint8   veh_longitude                   #车辆经度\n"
"uint8   veh_latitude                    #车辆纬度\n"
"uint8   Drive_mode                      #驾驶模式\n"
"uint8   Vehicle_Top_height              #车辆当前上装高度\n"
;
  }

  static const char* value(const ::custom_msgs::VehicleStat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::VehicleStat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.VehicleSpeed);
      stream.next(m.GearShiftPositon);
      stream.next(m.ParkSts);
      stream.next(m.ErrorCode);
      stream.next(m.RemainingMile);
      stream.next(m.TolMileage);
      stream.next(m.SAS_SteeringAngle);
      stream.next(m.EMS_EngineSpeed);
      stream.next(m.EMS_EngineThrottlePosition);
      stream.next(m.EMS_AccPedal);
      stream.next(m.EMS_BrakePedalStatus);
      stream.next(m.TCU_GearShiftPositon);
      stream.next(m.VehicleModle);
      stream.next(m.veh_speed);
      stream.next(m.veh_longitude);
      stream.next(m.veh_latitude);
      stream.next(m.Drive_mode);
      stream.next(m.Vehicle_Top_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleStat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::VehicleStat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::VehicleStat_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "VehicleSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.VehicleSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "GearShiftPositon: ";
    Printer<int8_t>::stream(s, indent + "  ", v.GearShiftPositon);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ParkSts: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ParkSts);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ErrorCode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ErrorCode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "RemainingMile: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.RemainingMile);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "TolMileage: ";
    Printer<float>::stream(s, indent + "  ", v.TolMileage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "SAS_SteeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.SAS_SteeringAngle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "EMS_EngineSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.EMS_EngineSpeed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "EMS_EngineThrottlePosition: ";
    Printer<float>::stream(s, indent + "  ", v.EMS_EngineThrottlePosition);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "EMS_AccPedal: ";
    Printer<float>::stream(s, indent + "  ", v.EMS_AccPedal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "EMS_BrakePedalStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EMS_BrakePedalStatus);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "TCU_GearShiftPositon: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TCU_GearShiftPositon);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "VehicleModle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.VehicleModle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "veh_speed: ";
    Printer<float>::stream(s, indent + "  ", v.veh_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "veh_longitude: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.veh_longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "veh_latitude: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.veh_latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Drive_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Drive_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Vehicle_Top_height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Vehicle_Top_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_VEHICLESTAT_H
