// Generated by gencpp from file custom_msgs/WarnRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WARNREQUEST_H
#define CUSTOM_MSGS_MESSAGE_WARNREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct WarnRequest_
{
  typedef WarnRequest_<ContainerAllocator> Type;

  WarnRequest_()
    : source(0)
    , code(0)  {
    }
  WarnRequest_(const ContainerAllocator& _alloc)
    : source(0)
    , code(0)  {
  (void)_alloc;
    }



   typedef uint8_t _source_type;
  _source_type source;

   typedef uint8_t _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::custom_msgs::WarnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::WarnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WarnRequest_

typedef ::custom_msgs::WarnRequest_<std::allocator<void> > WarnRequest;

typedef boost::shared_ptr< ::custom_msgs::WarnRequest > WarnRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::WarnRequest const> WarnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::WarnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::WarnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::WarnRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WarnRequest_<ContainerAllocator2> & rhs)
{
  return lhs.source == rhs.source &&
    lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::WarnRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WarnRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WarnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WarnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WarnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WarnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WarnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WarnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::WarnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a4d12632564889545d9dfc693560f12";
  }

  static const char* value(const ::custom_msgs::WarnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a4d126325648895ULL;
  static const uint64_t static_value2 = 0x45d9dfc693560f12ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::WarnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/WarnRequest";
  }

  static const char* value(const ::custom_msgs::WarnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::WarnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#异常报警服务\n"
"#------------------------------\n"
"uint8  source   #消息来源\n"
"uint8  code     #错误码\n"
;
  }

  static const char* value(const ::custom_msgs::WarnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::WarnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WarnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::WarnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::WarnRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.source);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WARNREQUEST_H
