// Generated by gencpp from file custom_msgs/WharfRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WHARFREQUEST_H
#define CUSTOM_MSGS_MESSAGE_WHARFREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct WharfRequest_
{
  typedef WharfRequest_<ContainerAllocator> Type;

  WharfRequest_()
    : enable(false)  {
    }
  WharfRequest_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::custom_msgs::WharfRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::WharfRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WharfRequest_

typedef ::custom_msgs::WharfRequest_<std::allocator<void> > WharfRequest;

typedef boost::shared_ptr< ::custom_msgs::WharfRequest > WharfRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::WharfRequest const> WharfRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::WharfRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::WharfRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::WharfRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WharfRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::WharfRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WharfRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WharfRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WharfRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WharfRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WharfRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WharfRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WharfRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::WharfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::custom_msgs::WharfRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::WharfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/WharfRequest";
  }

  static const char* value(const ::custom_msgs::WharfRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::WharfRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#------------------------------\n"
"#lidar码头检测\n"
"#------------------------------\n"
"bool enable          \n"
;
  }

  static const char* value(const ::custom_msgs::WharfRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::WharfRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WharfRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::WharfRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::WharfRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WHARFREQUEST_H
