// Generated by gencpp from file custom_msgs/Wharf.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WHARF_H
#define CUSTOM_MSGS_MESSAGE_WHARF_H

#include <ros/service_traits.h>


#include <custom_msgs/WharfRequest.h>
#include <custom_msgs/WharfResponse.h>


namespace custom_msgs
{

struct Wharf
{

typedef WharfRequest Request;
typedef WharfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wharf
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::Wharf > {
  static const char* value()
  {
    return "beeb1d84fce657cfd73dfadb6e25adb9";
  }

  static const char* value(const ::custom_msgs::Wharf&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::Wharf > {
  static const char* value()
  {
    return "custom_msgs/Wharf";
  }

  static const char* value(const ::custom_msgs::Wharf&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::WharfRequest> should match
// service_traits::MD5Sum< ::custom_msgs::Wharf >
template<>
struct MD5Sum< ::custom_msgs::WharfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Wharf >::value();
  }
  static const char* value(const ::custom_msgs::WharfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::WharfRequest> should match
// service_traits::DataType< ::custom_msgs::Wharf >
template<>
struct DataType< ::custom_msgs::WharfRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Wharf >::value();
  }
  static const char* value(const ::custom_msgs::WharfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::WharfResponse> should match
// service_traits::MD5Sum< ::custom_msgs::Wharf >
template<>
struct MD5Sum< ::custom_msgs::WharfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::Wharf >::value();
  }
  static const char* value(const ::custom_msgs::WharfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::WharfResponse> should match
// service_traits::DataType< ::custom_msgs::Wharf >
template<>
struct DataType< ::custom_msgs::WharfResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::Wharf >::value();
  }
  static const char* value(const ::custom_msgs::WharfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WHARF_H
