// Generated by gencpp from file custom_msgs/WindowCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WINDOWCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_WINDOWCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct WindowCmdRequest_
{
  typedef WindowCmdRequest_<ContainerAllocator> Type;

  WindowCmdRequest_()
    : WindowEnable(0)  {
    }
  WindowCmdRequest_(const ContainerAllocator& _alloc)
    : WindowEnable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _WindowEnable_type;
  _WindowEnable_type WindowEnable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TurnOff)
  #undef TurnOff
#endif
#if defined(_WIN32) && defined(Close)
  #undef Close
#endif
#if defined(_WIN32) && defined(Open)
  #undef Open
#endif

  enum {
    TurnOff = 0u,
    Close = 1u,
    Open = 2u,
  };


  typedef boost::shared_ptr< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WindowCmdRequest_

typedef ::custom_msgs::WindowCmdRequest_<std::allocator<void> > WindowCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::WindowCmdRequest > WindowCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::WindowCmdRequest const> WindowCmdRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::WindowCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::WindowCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WindowCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.WindowEnable == rhs.WindowEnable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::WindowCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WindowCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a816e263056967e58a0280db485583fb";
  }

  static const char* value(const ::custom_msgs::WindowCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa816e263056967e5ULL;
  static const uint64_t static_value2 = 0x8a0280db485583fbULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/WindowCmdRequest";
  }

  static const char* value(const ::custom_msgs::WindowCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#----------------------------------------------------------------\n"
"\n"
"#请求---------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 TurnOff=0\n"
"uint8 Close=1\n"
"uint8 Open=2\n"
"#\n"
"uint8 WindowEnable\n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::WindowCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.WindowEnable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WindowCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::WindowCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::WindowCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "WindowEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.WindowEnable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WINDOWCMDREQUEST_H
