// Generated by gencpp from file custom_msgs/WipersCmdRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_WIPERSCMDREQUEST_H
#define CUSTOM_MSGS_MESSAGE_WIPERSCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct WipersCmdRequest_
{
  typedef WipersCmdRequest_<ContainerAllocator> Type;

  WipersCmdRequest_()
    : WipersEnable(0)  {
    }
  WipersCmdRequest_(const ContainerAllocator& _alloc)
    : WipersEnable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _WipersEnable_type;
  _WipersEnable_type WipersEnable;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(TurnOff)
  #undef TurnOff
#endif
#if defined(_WIN32) && defined(LowSpeed)
  #undef LowSpeed
#endif
#if defined(_WIN32) && defined(HighSpeed)
  #undef HighSpeed
#endif

  enum {
    TurnOff = 0u,
    LowSpeed = 6u,
    HighSpeed = 7u,
  };


  typedef boost::shared_ptr< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WipersCmdRequest_

typedef ::custom_msgs::WipersCmdRequest_<std::allocator<void> > WipersCmdRequest;

typedef boost::shared_ptr< ::custom_msgs::WipersCmdRequest > WipersCmdRequestPtr;
typedef boost::shared_ptr< ::custom_msgs::WipersCmdRequest const> WipersCmdRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::WipersCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::WipersCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WipersCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.WipersEnable == rhs.WipersEnable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::WipersCmdRequest_<ContainerAllocator1> & lhs, const ::custom_msgs::WipersCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "504817eeef3d5736066562c0d4ca65ea";
  }

  static const char* value(const ::custom_msgs::WipersCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x504817eeef3d5736ULL;
  static const uint64_t static_value2 = 0x066562c0d4ca65eaULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/WipersCmdRequest";
  }

  static const char* value(const ::custom_msgs::WipersCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#---------------------------------------------------------------\n"
"# 作者 ：杨东\n"
"# 时间 ：2019.08.12\n"
"# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队\n"
"# 说明 ：\n"
"#      BCM BCM_Wipers 雨刮控制\n"
"#         0：停\n"
"#         6：低速刮刷\n"
"#         7：高速刮刷\n"
"#----------------------------------------------------------------\n"
"\n"
"#请求---------------------------------------------------------\n"
"##定义赋值枚举\n"
"uint8 TurnOff=0\n"
"uint8 LowSpeed=6\n"
"uint8 HighSpeed=7\n"
"#\n"
"uint8 WipersEnable   \n"
"\n"
;
  }

  static const char* value(const ::custom_msgs::WipersCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.WipersEnable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WipersCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::WipersCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::WipersCmdRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "WipersEnable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.WipersEnable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_WIPERSCMDREQUEST_H
